'use client';

import React from 'react';

interface MissionsHeaderProps {
  theme: {
    bg: string;
    bgCard: string;
    bgInside: string;
    border: string;
    tPrimary: string;
    tSecondary: string;
    tTertiary: string;
    accentLight: string;
  };
  xp: number;
  missionOnlyStreak: number;
}

export default function MissionsHeader({ theme, xp, missionOnlyStreak }: MissionsHeaderProps) {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 24,
        flexWrap: 'wrap',
        gap: 16,
      }}
    >
      <div className="page-header" style={{ marginBottom: 0 }}>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 24, fontWeight: 800, color: theme.tPrimary }}>
          Daily Missions
        </h1>
        <p style={{ color: theme.tSecondary, fontSize: 13 }}>
          Adaptive challenges dynamically generated by AI to close gaps between Current & Future Self.
        </p>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
        <button
          onClick={() => {
            if (typeof window !== 'undefined') {
              const doc = document.documentElement;
              const isDark = doc.getAttribute('data-theme') === 'dark';
              doc.setAttribute('data-theme', isDark ? 'light' : 'dark');
              window.dispatchEvent(new Event('theme-change'));
            }
          }}
          style={{
            background: theme.bgInside,
            border: `1.5px solid ${theme.border}`,
            color: theme.tPrimary,
            padding: '8px 16px',
            borderRadius: 12,
            fontSize: 12,
            fontWeight: 800,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
          }}
        >
          🌗 Toggle Theme
        </button>
      </div>

      {/* Streak & XP info card */}
      <div style={{ display: 'flex', gap: 10 }}>
        <div
          style={{
            background: theme.bgCard,
            border: `1px solid ${theme.border}`,
            borderRadius: 16,
            padding: '12px 18px',
            textAlign: 'center',
            boxShadow: 'var(--shadow-sm)',
            minWidth: 90,
          }}
        >
          <div style={{ fontSize: 22, lineHeight: 1 }}>⭐</div>
          <div
            style={{
              fontFamily: 'var(--font-display)',
              fontSize: 20,
              fontWeight: 800,
              color: 'var(--accent)',
              letterSpacing: '-0.5px',
              marginTop: 2,
            }}
          >
            {xp.toLocaleString()}
          </div>
          <div
            style={{
              fontSize: 9,
              color: theme.tTertiary,
              letterSpacing: '0.8px',
              textTransform: 'uppercase',
              fontFamily: 'var(--font-mono)',
              fontWeight: 600,
            }}
          >
            Total XP
          </div>
        </div>
        <div
          style={{
            background: missionOnlyStreak > 0 ? 'var(--amber-light)' : theme.bgCard,
            border: `1px solid ${missionOnlyStreak > 0 ? '#fde68a' : theme.border}`,
            borderRadius: 16,
            padding: '12px 18px',
            textAlign: 'center',
            boxShadow: 'var(--shadow-sm)',
            minWidth: 90,
          }}
        >
          <div style={{ fontSize: 22, lineHeight: 1 }}>🔥</div>
          <div
            style={{
              fontFamily: 'var(--font-display)',
              fontSize: 20,
              fontWeight: 800,
              color: 'var(--amber)',
              letterSpacing: '-0.5px',
              marginTop: 2,
            }}
          >
            {missionOnlyStreak}
          </div>
          <div
            style={{
              fontSize: 9,
              color: 'var(--amber)',
              letterSpacing: '0.8px',
              textTransform: 'uppercase',
              fontFamily: 'var(--font-mono)',
              fontWeight: 600,
            }}
          >
            Day Streak
          </div>
        </div>
      </div>
    </div>
  );
}
