// apps/web/src/lib/pathway/competencyCatalog.ts
// Authoritative V1 Competency Taxonomy for PinIT Career OS

import { CompetencyDefinition } from './competencySchema';

export const COMPETENCY_CATALOG_V1: CompetencyDefinition[] = [
  // ── TECHNICAL DOMAIN (Software Engineering, Backend & Systems) ───────────────
  {
    id: 'comp_comp_fundamentals_l0',
    version: '1.0.0',
    title: 'Computer Architecture & Operating Systems Concepts',
    domain: 'tech',
    level: 'L0',
    description: 'Understands CPU registers, RAM memory hierarchy, kernel space vs user space, and basic process lifecycles.',
    prerequisites: [],
    evidenceRequirements: [
      { evidenceClass: 'knowledge', minScore: 70, minCount: 1, minimumDifficulty: 'basic', requiredSourceTypes: ['quest'] },
    ],
    classWeights: { knowledge: 1.0 },
  },
  {
    id: 'comp_git_version_control_l1',
    version: '1.0.0',
    title: 'Git Version Control & Collaborative Workflow',
    domain: 'tech',
    level: 'L1',
    description: 'Branches, commits, merges, merge conflict resolution, pull request lifecycles, and git rebase fundamentals.',
    prerequisites: ['comp_comp_fundamentals_l0'],
    evidenceRequirements: [
      { evidenceClass: 'knowledge', minScore: 75, minCount: 1, minimumDifficulty: 'basic' },
      { evidenceClass: 'application', minScore: 80, minCount: 2, minDistinctFamilies: 1, minimumDifficulty: 'basic', requiredSourceTypes: ['project'] },
    ],
    verificationRequirements: {
      requiredArtifacts: ['github_repo', 'commit_sha'],
      requireExternalProvenance: true,
    },
    classWeights: { knowledge: 0.3, application: 0.7 },
  },
  {
    id: 'comp_java_syntax_oop_l1',
    version: '1.0.0',
    title: 'Java Core Syntax, Data Types & Object-Oriented Principles',
    domain: 'tech',
    level: 'L1',
    description: 'Variables, primitive vs reference types, control flow, encapsulation, inheritance, polymorphism, and exception handling.',
    prerequisites: ['comp_comp_fundamentals_l0'],
    evidenceRequirements: [
      { evidenceClass: 'knowledge', minScore: 75, minCount: 2, minimumDifficulty: 'basic' },
      { evidenceClass: 'application', minScore: 75, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'basic' },
    ],
    classWeights: { knowledge: 0.4, application: 0.6 },
  },
  {
    id: 'comp_python_syntax_data_l1',
    version: '1.0.0',
    title: 'Python Core Syntax, Collections & Functional Primitives',
    domain: 'tech',
    level: 'L1',
    description: 'Data structures (lists, tuples, dicts, sets), list comprehensions, lambda functions, modules, and file I/O operations.',
    prerequisites: ['comp_comp_fundamentals_l0'],
    evidenceRequirements: [
      { evidenceClass: 'knowledge', minScore: 75, minCount: 2, minimumDifficulty: 'basic' },
      { evidenceClass: 'application', minScore: 75, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'basic' },
    ],
    classWeights: { knowledge: 0.4, application: 0.6 },
  },
  {
    id: 'comp_dsa_linear_trees_l2',
    version: '1.0.0',
    title: 'Data Structures: Linear Structures, Trees & Hash Maps',
    domain: 'tech',
    level: 'L2',
    description: 'Asymptotic Big-O time and space complexity, Linked Lists, Stacks, Queues, Binary Search Trees, and Hash Collisions.',
    prerequisites: ['comp_java_syntax_oop_l1'],
    evidenceRequirements: [
      { evidenceClass: 'knowledge', minScore: 75, minCount: 2, minimumDifficulty: 'intermediate' },
      { evidenceClass: 'application', minScore: 80, minCount: 3, minDistinctFamilies: 2, minimumDifficulty: 'intermediate' },
      { evidenceClass: 'debugging', minScore: 70, minCount: 1, minimumDifficulty: 'intermediate' },
    ],
    classWeights: { knowledge: 0.25, application: 0.55, debugging: 0.20 },
  },
  {
    id: 'comp_concurrency_threads_l2',
    version: '1.0.0',
    title: 'Multi-Threading, Synchronization & Concurrency Control',
    domain: 'tech',
    level: 'L2',
    description: 'Thread lifecycles, race condition diagnostics, volatile variables, mutexes, synchronized blocks, and thread pools.',
    prerequisites: ['comp_java_syntax_oop_l1'],
    evidenceRequirements: [
      { evidenceClass: 'knowledge', minScore: 75, minCount: 2, minimumDifficulty: 'intermediate' },
      { evidenceClass: 'application', minScore: 75, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'intermediate' },
      { evidenceClass: 'debugging', minScore: 75, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'intermediate', requiredSourceTypes: ['bug_lab'] },
    ],
    criticalFailureRules: [
      { code: 'DEADLOCK_UNHANDLED', description: 'Code execution blocked by undetected circular lock acquisition', blocksMastery: true },
    ],
    classWeights: { knowledge: 0.25, application: 0.40, debugging: 0.35 },
  },
  {
    id: 'comp_database_sql_internals_l3',
    version: '1.0.0',
    title: 'Relational Database Internals, Indexes & ACID Transactions',
    domain: 'tech',
    level: 'L3',
    description: 'B-Tree indexes, query execution plans, transaction isolation levels (Read Committed vs Serializable), and connection pooling.',
    prerequisites: ['comp_dsa_linear_trees_l2'],
    evidenceRequirements: [
      { evidenceClass: 'application', minScore: 80, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'advanced' },
      { evidenceClass: 'debugging', minScore: 75, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'advanced', requiredSourceTypes: ['bug_lab'] },
      { evidenceClass: 'production', minScore: 75, minCount: 1, minimumDifficulty: 'advanced' },
    ],
    criticalFailureRules: [
      { code: 'SQL_INJECTION_VULNERABLE', description: 'Raw SQL concatenation detected without parameterized queries', blocksMastery: true },
    ],
    classWeights: { application: 0.35, debugging: 0.35, production: 0.30 },
  },
  {
    id: 'comp_backend_apis_frameworks_l3',
    version: '1.0.0',
    title: 'Production Backend APIs, Middleware & Service Architecture',
    domain: 'tech',
    level: 'L3',
    description: 'RESTful API contracts, JWT authentication, request validation, error middleware, unit & integration testing with mocking.',
    prerequisites: ['comp_concurrency_threads_l2', 'comp_git_version_control_l1'],
    evidenceRequirements: [
      { evidenceClass: 'application', minScore: 80, minCount: 2, minimumDifficulty: 'advanced' },
      { evidenceClass: 'production', minScore: 80, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'advanced', requiredSourceTypes: ['project'] },
      { evidenceClass: 'debugging', minScore: 75, minCount: 1, minimumDifficulty: 'advanced' },
    ],
    verificationRequirements: {
      requiredArtifacts: ['github_repo', 'commit_sha'],
      requireExternalProvenance: true,
    },
    classWeights: { application: 0.30, production: 0.45, debugging: 0.25 },
  },
  {
    id: 'comp_distributed_systems_caching_l4',
    version: '1.0.0',
    title: 'Distributed Systems, High-Throughput Caching & Messaging',
    domain: 'tech',
    level: 'L4',
    description: 'Redis caching strategies (Cache-Aside, Write-Through), Kafka event pub/sub, sharding, distributed locking, and rate limiting.',
    prerequisites: ['comp_database_sql_internals_l3', 'comp_backend_apis_frameworks_l3'],
    evidenceRequirements: [
      { evidenceClass: 'architecture', minScore: 80, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'advanced', requiredSourceTypes: ['whiteboard'] },
      { evidenceClass: 'debugging', minScore: 75, minCount: 2, minimumDifficulty: 'advanced', requiredSourceTypes: ['bug_lab'] },
      { evidenceClass: 'defense', minScore: 75, minCount: 1, minimumDifficulty: 'advanced' },
    ],
    verificationRequirements: {
      requiredArtifacts: ['whiteboard_diagram'],
      requiredEvaluatorTypes: ['ai', 'human_mentor'],
      minDefenseScore: 75,
    },
    classWeights: { architecture: 0.45, debugging: 0.35, defense: 0.20 },
  },
  {
    id: 'comp_cicd_cloud_devops_l4',
    version: '1.0.0',
    title: 'Docker Containerization, CI/CD Automation & Cloud Hosting',
    domain: 'tech',
    level: 'L4',
    description: 'Multi-stage Docker builds, GitHub Actions automated CI pipelines, secret management, container orchestration, and observability.',
    prerequisites: ['comp_backend_apis_frameworks_l3'],
    evidenceRequirements: [
      { evidenceClass: 'application', minScore: 80, minCount: 2, minimumDifficulty: 'advanced' },
      { evidenceClass: 'production', minScore: 80, minCount: 2, minimumDifficulty: 'advanced', requiredSourceTypes: ['project'] },
    ],
    verificationRequirements: {
      requiredArtifacts: ['github_repo', 'commit_sha', 'live_url'],
      requireExternalProvenance: true,
    },
    classWeights: { application: 0.40, production: 0.60 },
  },
  {
    id: 'comp_production_engineering_residency_l5',
    version: '1.0.0',
    title: 'Production Engineering Residency & Live Capstone Defense',
    domain: 'tech',
    level: 'L5',
    description: 'Operates inside simulated Agile company: ships full-stack SaaS product, manages incident change requests, and defends architecture.',
    prerequisites: ['comp_distributed_systems_caching_l4', 'comp_cicd_cloud_devops_l4'],
    evidenceRequirements: [
      { evidenceClass: 'production', minScore: 85, minCount: 3, minDistinctFamilies: 3, minimumDifficulty: 'production', requiredSourceTypes: ['capstone', 'project'] },
      { evidenceClass: 'architecture', minScore: 80, minCount: 2, minimumDifficulty: 'production', requiredSourceTypes: ['whiteboard'] },
      { evidenceClass: 'defense', minScore: 80, minCount: 1, minimumDifficulty: 'production' },
    ],
    verificationRequirements: {
      requiredArtifacts: ['github_repo', 'commit_sha', 'live_url', 'whiteboard_diagram'],
      requiredEvaluatorTypes: ['hybrid'],
      requireExternalProvenance: true,
      minDefenseScore: 80,
    },
    classWeights: { production: 0.50, architecture: 0.25, defense: 0.25 },
  },

  // ── DATA & ANALYTICS DOMAIN ──────────────────────────────────────────────────
  {
    id: 'comp_data_spreadsheets_quant_l1',
    version: '1.0.0',
    title: 'Spreadsheets, Data Modeling & Quantitative Analysis',
    domain: 'data',
    level: 'L1',
    description: 'Advanced Excel/Sheets formulas (XLOOKUP, INDEX/MATCH), Pivot Tables, descriptive statistics, and data hygiene.',
    prerequisites: ['comp_comp_fundamentals_l0'],
    evidenceRequirements: [
      { evidenceClass: 'knowledge', minScore: 75, minCount: 1, minimumDifficulty: 'basic' },
      { evidenceClass: 'application', minScore: 80, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'basic' },
    ],
    classWeights: { knowledge: 0.35, application: 0.65 },
  },
  {
    id: 'comp_data_sql_analytics_l2',
    version: '1.0.0',
    title: 'SQL Data Extraction, Window Functions & Aggregation',
    domain: 'data',
    level: 'L2',
    description: 'Complex SQL joins, Common Table Expressions (CTEs), Window Functions (ROW_NUMBER, DENSE_RANK, LAG/LEAD), and group aggregations.',
    prerequisites: ['comp_data_spreadsheets_quant_l1'],
    evidenceRequirements: [
      { evidenceClass: 'application', minScore: 80, minCount: 3, minDistinctFamilies: 2, minimumDifficulty: 'intermediate' },
      { evidenceClass: 'debugging', minScore: 75, minCount: 1, minimumDifficulty: 'intermediate' },
    ],
    classWeights: { application: 0.70, debugging: 0.30 },
  },
  {
    id: 'comp_data_bi_dashboards_l3',
    version: '1.0.0',
    title: 'Business Intelligence Dashboards & Predictive Storytelling',
    domain: 'data',
    level: 'L3',
    description: 'Power BI / Tableau data modeling, DAX measures, automated ETL pipelines, and executive KPI dashboard visualization.',
    prerequisites: ['comp_data_sql_analytics_l2'],
    evidenceRequirements: [
      { evidenceClass: 'application', minScore: 80, minCount: 2, minimumDifficulty: 'advanced' },
      { evidenceClass: 'production', minScore: 80, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'advanced', requiredSourceTypes: ['project'] },
    ],
    classWeights: { application: 0.40, production: 0.60 },
  },

  // ── AI & MACHINE LEARNING DOMAIN ─────────────────────────────────────────────
  {
    id: 'comp_ai_literacy_prompting_l1',
    version: '1.0.0',
    title: 'AI Literacy, LLM Prompt Engineering & Guardrails',
    domain: 'ai',
    level: 'L1',
    description: 'Transformer architecture intuition, zero-shot/few-shot prompting, structured JSON schema outputs, and hallucinations mitigation.',
    prerequisites: ['comp_comp_fundamentals_l0'],
    evidenceRequirements: [
      { evidenceClass: 'knowledge', minScore: 75, minCount: 1, minimumDifficulty: 'basic' },
      { evidenceClass: 'application', minScore: 80, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'basic' },
    ],
    classWeights: { knowledge: 0.35, application: 0.65 },
  },
  {
    id: 'comp_ai_rag_vector_search_l3',
    version: '1.0.0',
    title: 'Vector Embeddings, Semantic Search & RAG Architecture',
    domain: 'ai',
    level: 'L3',
    description: 'Text chunking strategies, vector embeddings, cosine distance indexing (Pinecone/pgvector), and contextual reranking.',
    prerequisites: ['comp_ai_literacy_prompting_l1', 'comp_python_syntax_data_l1'],
    evidenceRequirements: [
      { evidenceClass: 'application', minScore: 80, minCount: 2, minimumDifficulty: 'advanced' },
      { evidenceClass: 'production', minScore: 80, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'advanced', requiredSourceTypes: ['project'] },
    ],
    classWeights: { application: 0.40, production: 0.60 },
  },

  // ── COMMUNICATION & WORKPLACE DOMAIN ─────────────────────────────────────────
  {
    id: 'comp_comm_star_interview_l2',
    version: '1.0.0',
    title: 'STAR Technical & Behavioral Interview Articulation',
    domain: 'communication',
    level: 'L2',
    description: 'Delivers structured Situation-Task-Action-Result responses with quantitative metrics and executive tone.',
    prerequisites: ['comp_comp_fundamentals_l0'],
    evidenceRequirements: [
      { evidenceClass: 'application', minScore: 75, minCount: 2, minimumDifficulty: 'intermediate' },
      { evidenceClass: 'defense', minScore: 80, minCount: 2, minDistinctFamilies: 2, minimumDifficulty: 'intermediate' },
    ],
    verificationRequirements: {
      requiredEvaluatorTypes: ['ai', 'human_mentor'],
      minDefenseScore: 80,
    },
    classWeights: { application: 0.40, defense: 0.60 },
  },
];
