'use client';

import Link from 'next/link';
import PublicNavbar from '@/components/nav/PublicNavbar';
import PublicFooter from '@/components/nav/PublicFooter';

export default function TermsPage() {
  return (
    <main style={{
      minHeight: '100vh',
      background: 'var(--bg)',
      color: 'var(--t1)',
      display: 'flex',
      flexDirection: 'column',
      position: 'relative',
      overflow: 'hidden'
    }}>
      {/* Universal Public Navbar */}
      <PublicNavbar />

      {/* Content Area */}
      <div style={{
        flex: 1,
        maxWidth: '800px',
        width: '100%',
        margin: '0 auto',
        padding: '60px 24px',
        zIndex: 10
      }}>
        <div style={{
          background: 'rgba(10, 15, 26, 0.65)',
          backdropFilter: 'blur(20px)',
          WebkitBackdropFilter: 'blur(20px)',
          border: '1px solid rgba(255, 255, 255, 0.08)',
          borderRadius: '24px',
          padding: '40px',
          boxShadow: '0 20px 40px rgba(0, 0, 0, 0.3)'
        }}>
          <h1 style={{
            fontSize: '2rem',
            fontWeight: 900,
            marginBottom: '10px',
            background: 'linear-gradient(to right, #a5b4fc, #34d399)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            fontFamily: 'var(--font-display)'
          }}>📜 Terms of Service</h1>
          <p style={{ fontSize: '12.5px', color: 'var(--t4)', fontFamily: 'var(--font-mono)', marginBottom: '32px' }}>
            Last Updated: June 12, 2026
          </p>

          <section style={{ display: 'flex', flexDirection: 'column', gap: '24px', fontSize: '14px', lineHeight: '1.6', color: 'var(--t2)' }}>
            <div>
              <h2 style={{ fontSize: '16px', fontWeight: 700, color: 'var(--t1)', marginBottom: '8px' }}>1. Acceptance of Terms</h2>
              <p>
                By accessing or using the PinIT Career OS web application, you agree to comply with and be bound by these Terms of Service. If you do not agree, you must not access or use the application.
              </p>
            </div>

            <div>
              <h2 style={{ fontSize: '16px', fontWeight: 700, color: 'var(--t1)', marginBottom: '8px' }}>2. Account Responsibility &amp; Academic Integrity</h2>
              <p>
                You are responsible for maintaining the confidentiality of your credentials. You agree that all socratic coding quests, exams, and diagnostic assessments will be completed by you personally. Attempting to bypass exam tab-switching checks or upload fabricated validation proofs will result in immediate Trust Score deductions or account suspension.
              </p>
            </div>

            <div>
              <h2 style={{ fontSize: '16px', fontWeight: 700, color: 'var(--t1)', marginBottom: '8px' }}>3. Cryptographic Signature Service</h2>
              <p>
                The Sentinel verification service is provided as-is. We guarantee that the SHA-256 hashes generated by our platform are unique to the inputs provided, but the verification status depends on the validity of external organizational credentials uploaded to your Secure Vault.
              </p>
            </div>

            <div>
              <h2 style={{ fontSize: '16px', fontWeight: 700, color: 'var(--t1)', marginBottom: '8px' }}>4. Premium Services</h2>
              <p>
                Access to certain socratic quests, live mock assessment interviews, and specialized recruiter filters may require purchase. All payments processed via Razorpay are subject to their respective terms and conditions.
              </p>
            </div>

            <div>
              <h2 style={{ fontSize: '16px', fontWeight: 700, color: 'var(--t1)', marginBottom: '8px' }}>5. Modifications &amp; Contact</h2>
              <p>
                We reserve the right to modify these terms at any time. Continued use of the platform constitutes agreement to the updated terms. If you have questions about these terms, please contact us at our <Link href="/contact" style={{ color: 'var(--accent)', textDecoration: 'none' }}>Contact Page</Link>.
              </p>
            </div>
          </section>
        </div>
      </div>

      {/* Universal Public Footer */}
      <PublicFooter />
    </main>
  );
}
