/**
 * Generates the server-owned quest test-suite registry consumed by
 * supabase/functions/verify-quest/index.ts (Stage 1, §3.1 + §3.2).
 *
 * BEFORE this generator existed, `QUEST_TEST_SUITES` in the edge function was a
 * 4-entry hand-written map (`fizzbuzz`, `reverser`, `palindrome`, `generic`).
 * No real quest ID (e.g. `react-basics-exam-day-1`) was ever a key, so EVERY
 * real submission fell through to `QUEST_TEST_SUITES.generic`, whose body is
 * `// Generic verification pass — no code test required` — code that never
 * throws, so every submission "passed" regardless of content.
 *
 * This script reads the SAME authoritative COURSES_REGISTRY module the app
 * ships (already validated against the running app by scripts/content-qa.ts
 * and scripts/runtime-binding.test.ts), extracts every quest's real
 * `testSuite`, and emits a generated TypeScript file the edge function imports.
 * The client never supplies this data — it is built at generation time from
 * course source, deployed with the function, and looked up by exact quest ID.
 *
 * Run:  node scripts/generate-quest-test-suites.js
 */

import * as fs from 'fs';
import * as path from 'path';
import { COURSES_REGISTRY } from '../src/lib/data/coursesData';

const OUTPUT_PATH = path.join(
  __dirname, '..', 'supabase', 'functions', 'verify-quest', 'questTestSuites.generated.ts',
);

// Legacy hand-written entries predating this generator. Preserved for any
// caller still referencing these bespoke IDs directly; harmless to keep.
const LEGACY_TEST_SUITES: Record<string, string> = {
  fizzbuzz: `
    if (typeof fizzBuzz !== 'function') throw new Error("Method fizzBuzz(int n) not found.");
    if (fizzBuzz(3) !== "Fizz") throw new Error("Failed: fizzBuzz(3) should return 'Fizz'");
    if (fizzBuzz(5) !== "Buzz") throw new Error("Failed: fizzBuzz(5) should return 'Buzz'");
    if (fizzBuzz(15) !== "FizzBuzz") throw new Error("Failed: fizzBuzz(15) should return 'FizzBuzz'");
    if (fizzBuzz(7) !== "7") throw new Error("Failed: fizzBuzz(7) should return '7'");
    if (fizzBuzz(1) !== "1") throw new Error("Failed: fizzBuzz(1) should return '1'");
  `,
  reverser: `
    if (typeof reverseString !== 'function') throw new Error("Method reverseString(String s) not found.");
    if (reverseString("hello") !== "olleh") throw new Error("Failed: reverseString('hello') !== 'olleh'");
    if (reverseString("") !== "") throw new Error("Failed: reverseString('') should return ''");
    if (reverseString("a") !== "a") throw new Error("Failed: reverseString('a') !== 'a'");
    if (reverseString("abcde") !== "edcba") throw new Error("Failed: reverseString('abcde') !== 'edcba'");
  `,
  palindrome: `
    if (typeof isPalindrome !== 'function') throw new Error("Method isPalindrome(String s) not found.");
    if (!isPalindrome("racecar")) throw new Error("Failed: 'racecar' is a palindrome");
    if (isPalindrome("hello")) throw new Error("Failed: 'hello' is not a palindrome");
    if (!isPalindrome("a")) throw new Error("Failed: 'a' is a palindrome");
  `,
};

function main(): void {
  const registry: Record<string, string> = { ...LEGACY_TEST_SUITES };
  let questCount = 0;
  let skippedEmpty = 0;
  const collisions: string[] = [];

  for (const course of COURSES_REGISTRY) {
    for (const quest of course.quests ?? []) {
      if (quest.category !== 'exam' && quest.category !== 'assignment') continue;
      const testSuite = quest.testSuite ?? '';
      if (!testSuite.trim()) { skippedEmpty++; continue; }
      if (registry[quest.id] && registry[quest.id] !== testSuite) collisions.push(quest.id);
      registry[quest.id] = testSuite;
      questCount++;
    }
  }

  if (collisions.length) {
    throw new Error(`Quest ID collision(s) with differing test suites: ${collisions.join(', ')}`);
  }

  const entries = Object.entries(registry)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, suite]) => `  ${JSON.stringify(id)}: ${JSON.stringify(suite)},`)
    .join('\n');

  const output = `// AUTO-GENERATED by scripts/generate-quest-test-suites.ts — DO NOT EDIT BY HAND.
// Regenerate with: node scripts/generate-quest-test-suites.js
//
// Server-owned quest test-suite registry (Stage 1, §3.1 + §3.2). Built from
// the authoritative COURSES_REGISTRY course data at generation time. The
// client can identify a quest by ID; it cannot supply or override the grader.
// An unknown quest ID has no entry here and MUST fail closed in the caller —
// see verify-quest/index.ts.

export const QUEST_TEST_SUITES: Record<string, string> = {
${entries}
};

export const QUEST_TEST_SUITES_META = {
  generatedAt: ${JSON.stringify(new Date().toISOString())},
  totalEntries: ${Object.keys(registry).length},
  fromCourseRegistry: ${questCount},
  legacyEntries: ${Object.keys(LEGACY_TEST_SUITES).length},
};
`;

  fs.writeFileSync(OUTPUT_PATH, output, 'utf8');

  console.log(`Quest test-suite registry generated: ${OUTPUT_PATH}`);
  console.log(`  from COURSES_REGISTRY : ${questCount} quests`);
  console.log(`  legacy hand-written   : ${Object.keys(LEGACY_TEST_SUITES).length} quests`);
  console.log(`  skipped (empty suite) : ${skippedEmpty} quests`);
  console.log(`  total registry size   : ${Object.keys(registry).length} entries`);
}

main();
