/**
 * Generates supabase/diagnostics/production_inventory.sql: a read-only query that tells you, for every
 * SQL file in this repo, whether the tables, functions and columns it creates exist in a database.
 *
 * How: builds a throwaway database file by file and records what each file adds.
 * Run: npx tsx scripts/generate_db_inventory.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import type { PGlite } from '@electric-sql/pglite';
import { applyFiles, createPlatformDb, freshBuildFiles, ROOT } from '../tests/helpers/db';

export const INVENTORY_PATH = path.join(ROOT, 'supabase', 'diagnostics', 'production_inventory.sql');

type Kind = 'table' | 'function' | 'column';
interface Expected {
  file: string;
  kind: Kind;
  name: string;
}

async function snapshot(db: PGlite) {
  const tables = await db.query<{ n: string }>(
    `select 'public.' || c.relname as n
       from pg_class c join pg_namespace s on s.oid = c.relnamespace
      where s.nspname = 'public' and c.relkind in ('r', 'v', 'm', 'p')`
  );
  const functions = await db.query<{ n: string }>(
    `select distinct 'public.' || p.proname as n
       from pg_proc p join pg_namespace s on s.oid = p.pronamespace
      where s.nspname = 'public'`
  );
  const columns = await db.query<{ n: string }>(
    `select 'public.' || table_name || '.' || column_name as n
       from information_schema.columns where table_schema = 'public'`
  );
  return {
    tables: new Set(tables.rows.map((r) => r.n)),
    functions: new Set(functions.rows.map((r) => r.n)),
    columns: new Set(columns.rows.map((r) => r.n)),
  };
}

export async function collectExpectedObjects(): Promise<{ expected: Expected[]; filesWithoutNewObjects: string[] }> {
  const db = await createPlatformDb();
  const expected: Expected[] = [];
  const filesWithoutNewObjects: string[] = [];
  try {
    let before = await snapshot(db);
    for (const file of freshBuildFiles()) {
      const failures = await applyFiles(db, [file]);
      if (failures.length) throw new Error(`${file} failed to apply: ${failures[0].error}`);
      const after = await snapshot(db);
      const added: Expected[] = [];
      for (const t of after.tables) if (!before.tables.has(t)) added.push({ file, kind: 'table', name: t });
      for (const f of after.functions) if (!before.functions.has(f)) added.push({ file, kind: 'function', name: f });
      for (const c of after.columns) {
        const table = c.split('.').slice(0, 2).join('.');
        // Columns of brand-new tables are covered by the table itself.
        if (!before.columns.has(c) && before.tables.has(table)) added.push({ file, kind: 'column', name: c });
      }
      if (added.length) expected.push(...added.sort((a, b) => a.name.localeCompare(b.name)));
      else filesWithoutNewObjects.push(file);
      before = after;
    }
  } finally {
    await db.close();
  }
  return { expected, filesWithoutNewObjects };
}

export function renderInventorySql(expected: Expected[], filesWithoutNewObjects: string[]): string {
  const order = new Map<string, number>();
  for (const e of expected) if (!order.has(e.file)) order.set(e.file, order.size + 1);
  const values = expected
    .map((e) => `    (${order.get(e.file)}, '${e.file}', '${e.kind}', '${e.name}')`)
    .join(',\n');
  return `-- Generated by scripts/generate_db_inventory.ts from the SQL files in this repo. Do not edit by hand.
-- READ-ONLY: run it in the Supabase SQL editor to see which repo SQL files a database actually has.
-- status: applied = everything the file creates exists; PARTLY = some; NOT APPLIED = none.
-- Files that only change existing objects (policies, grants, function bodies) cannot be detected this way:
${filesWithoutNewObjects.map((f) => `--   ${f}`).join('\n')}
with expected(ord, file, kind, name) as (
  values
${values}
),
checked as (
  select e.ord, e.file, e.name,
    case e.kind
      when 'table' then to_regclass(e.name) is not null
      when 'function' then exists (
        select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and p.proname = split_part(e.name, '.', 2))
      else exists (
        select 1 from information_schema.columns c
         where c.table_schema = 'public'
           and c.table_name = split_part(e.name, '.', 2)
           and c.column_name = split_part(e.name, '.', 3))
    end as present
  from expected e
)
select file,
  case when bool_and(present) then 'applied' when bool_or(present) then 'PARTLY' else 'NOT APPLIED' end as status,
  (count(*) filter (where present)) || ' / ' || count(*) as objects_found,
  coalesce(string_agg(name, ', ' order by name) filter (where not present), '') as missing
from checked
group by ord, file
order by ord;
`;
}

async function main() {
  const { expected, filesWithoutNewObjects } = await collectExpectedObjects();
  fs.mkdirSync(path.dirname(INVENTORY_PATH), { recursive: true });
  fs.writeFileSync(INVENTORY_PATH, renderInventorySql(expected, filesWithoutNewObjects));
  console.log(`Wrote ${path.relative(ROOT, INVENTORY_PATH)}: ${expected.length} objects.`);
  console.log(`Files with no detectable new objects: ${filesWithoutNewObjects.length}`);
}

if (require.main === module) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
