// scripts/test_staging_telemetry_migration.ts
// Staging Database Isolation & Migration Validation for Telemetry Ingestion Boundary

import { PGlite } from '@electric-sql/pglite';
import fs from 'fs';
import path from 'path';

async function runStagingTelemetryMigrationTest() {
  console.log('========================================================================');
  console.log('🧪 STAGING TEST: TELEMETRY MIGRATION, GRANTS & ADVERSARIAL RLS AUDIT');
  console.log('========================================================================\n');

  const db = new PGlite();

  // 1. Setup Postgres roles (anon, authenticated, service_role)
  await db.exec(`
    CREATE ROLE anon NOLOGIN;
    CREATE ROLE authenticated NOLOGIN;
    CREATE ROLE service_role NOLOGIN;
    GRANT ALL ON SCHEMA public TO anon, authenticated, service_role;
  `);

  // 2. Load the actual migration file
  const migrationPath = path.join(process.cwd(), 'supabase', 'migrations', '20260904_create_client_telemetry.sql');
  const migrationSql = fs.readFileSync(migrationPath, 'utf8');
  await db.exec(migrationSql);

  console.log('  ✅ [PASS] Migration Applied: public.client_telemetry_events created with RLS enabled.\n');

  let passedChecks = 0;
  let totalChecks = 0;

  function assertCheck(name: string, condition: boolean, detail: string) {
    totalChecks++;
    if (condition) {
      passedChecks++;
      console.log(`  ✅ [PASS] ${name}: ${detail}`);
    } else {
      console.error(`  ❌ [FAIL] ${name}: ${detail}`);
      process.exit(1);
    }
  }

  // ── TEST 1: Anon valid INSERT ──
  try {
    await db.exec(`
      SET ROLE anon;
      INSERT INTO public.client_telemetry_events (
        client_id,
        client_reported_timestamp,
        release,
        route,
        error_type,
        sanitized_message,
        sanitized_stack,
        trust_classification
      ) VALUES (
        'tel_test_001',
        NOW(),
        'd0f3a65b68',
        '/dashboard',
        'UNHANDLED_EXCEPTION',
        'TypeError: Cannot read properties of undefined',
        'Error at App.tsx:12',
        'UNTRUSTED_CLIENT_OBSERVATION'
      );
      RESET ROLE;
    `);
    assertCheck('Anon Valid Insert', true, 'Anonymous client successfully inserted untrusted telemetry event.');
  } catch (err: any) {
    assertCheck('Anon Valid Insert', false, err.message);
  }

  // ── TEST 2: Verify Server-Derived Timestamp ──
  const record = await db.query<any>(`
    SELECT client_id, server_received_at, trust_classification
    FROM public.client_telemetry_events
    WHERE client_id = 'tel_test_001';
  `);
  assertCheck(
    'Server-Derived Timestamp',
    record.rows.length === 1 && record.rows[0].server_received_at !== null,
    `server_received_at was generated by PostgreSQL server (${record.rows[0]?.server_received_at})`
  );

  // ── TEST 3: Anon Fraudulent Classification Attempt (Tampering Check) ──
  let spoofBlocked = false;
  try {
    await db.exec(`
      SET ROLE anon;
      INSERT INTO public.client_telemetry_events (
        client_id, client_reported_timestamp, release, route, error_type, sanitized_message, trust_classification
      ) VALUES (
        'tel_spoof_002', NOW(), 'd0f3a65b68', '/admin', 'AUTH_BYPASS', 'Injected trusted signal', 'AUTHORITATIVE_SYSTEM_EVIDENCE'
      );
      RESET ROLE;
    `);
  } catch {
    spoofBlocked = true;
    await db.exec('RESET ROLE;');
  }
  assertCheck('Spoofed Classification Denial', spoofBlocked, 'Policy check rejected attempt to insert non-UNTRUSTED telemetry event.');

  // ── TEST 4: Anon Oversized Message Attempt (>1000 chars) ──
  let oversizeBlocked = false;
  try {
    const hugeMsg = 'E'.repeat(1500);
    await db.exec(`
      SET ROLE anon;
      INSERT INTO public.client_telemetry_events (
        client_id, client_reported_timestamp, release, route, error_type, sanitized_message, trust_classification
      ) VALUES (
        'tel_huge_003', NOW(), 'd0f3a65b68', '/dashboard', 'OVERSIZED', '${hugeMsg}', 'UNTRUSTED_CLIENT_OBSERVATION'
      );
      RESET ROLE;
    `);
  } catch {
    oversizeBlocked = true;
    await db.exec('RESET ROLE;');
  }
  assertCheck('Oversized Message Denial', oversizeBlocked, 'Check constraint rejected sanitized_message exceeding length threshold.');

  // ── TEST 5: Anon SELECT Exfiltration Denial ──
  let selectDenied = false;
  try {
    await db.exec(`
      SET ROLE anon;
      SELECT * FROM public.client_telemetry_events;
      RESET ROLE;
    `);
  } catch (err: any) {
    selectDenied = true;
    await db.exec('RESET ROLE;');
  }
  assertCheck('Anon SELECT Denial', selectDenied, 'PostgreSQL revoked SELECT privilege; anonymous client cannot read telemetry.');

  // ── TEST 6: Anon UPDATE Tampering Denial ──
  let updateDenied = false;
  try {
    await db.exec(`
      SET ROLE anon;
      UPDATE public.client_telemetry_events SET sanitized_message = 'tampered' WHERE client_id = 'tel_test_001';
      RESET ROLE;
    `);
  } catch {
    updateDenied = true;
    await db.exec('RESET ROLE;');
  }
  assertCheck('Anon UPDATE Denial', updateDenied, 'PostgreSQL revoked UPDATE privilege; anonymous client cannot modify records.');

  // ── TEST 7: Anon DELETE Denial ──
  let deleteDenied = false;
  try {
    await db.exec(`
      SET ROLE anon;
      DELETE FROM public.client_telemetry_events WHERE client_id = 'tel_test_001';
      RESET ROLE;
    `);
  } catch {
    deleteDenied = true;
    await db.exec('RESET ROLE;');
  }
  assertCheck('Anon DELETE Denial', deleteDenied, 'PostgreSQL revoked DELETE privilege; anonymous client cannot erase records.');

  // ── TEST 8: Service Role Management ──
  let serviceRoleSuccess = false;
  try {
    await db.exec('SET ROLE service_role;');
    const res = await db.query('SELECT COUNT(*) FROM public.client_telemetry_events;');
    serviceRoleSuccess = res.rows.length > 0;
    await db.exec('RESET ROLE;');
  } catch {
    await db.exec('RESET ROLE;');
  }
  assertCheck('Service Role Authority', serviceRoleSuccess, 'service_role maintains authorized query and diagnostic access.');

  console.log('\n========================================================================');
  console.log(`STAGING TELEMETRY AUDIT SCORECARD: ${passedChecks}/${totalChecks} PASSED`);
  console.log('STATUS: ✅ STAGING MIGRATION, RLS, AND GRANTS FULLY VERIFIED');
  console.log('========================================================================');
}

runStagingTelemetryMigrationTest().catch((err) => {
  console.error('Fatal staging test failure:', err);
  process.exit(1);
});