/**
 * Adaptive Teaching Engine (v4.0 Frozen Standard)
 * Strict, typed pedagogical contracts for beginner-first computer science education.
 */

// ── 1. Mastery State Machine ───────────────────────────────────────────────

export type MasteryLevel =
  | 'unknown'     // Never encountered
  | 'introduced'  // Block viewed
  | 'confused'    // Failed diagnostic or requested recovery
  | 'partial'     // Passed diagnostic with hints/guided help
  | 'practiced'   // Successfully completed guided sandbox step
  | 'understood'  // Passed concept diagnostic in taught context + micro-task
  | 'mastered';   // Independent novel transfer task + prediction evidence with 0 hints

export interface ConceptMasteryState {
  conceptId: string;
  studentId: string;
  state: MasteryLevel;
  attempts: number;
  correctAttempts: number;
  hintsUsed: number;
  misconceptionsTriggered: string[];
  selfReportedConfidence?: 1 | 2 | 3 | 4 | 5;
  transferEvidence: {
    novelTaskPassed: boolean;
    predictionPassed: boolean;
    explanationProvided?: string;
  };
  recoveryCount: number;
  mentorEscalated: boolean;
  lastAttemptAt: string;
}

// ── 2. Misconception Taxonomy ──────────────────────────────────────────────

export type JavaMisconceptionId =
  | 'MC_JAVA_EXECUTION_ORDER'
  | 'MC_JAVA_VARIABLE_REASSIGNMENT'
  | 'MC_JAVA_PASS_BY_VALUE'
  | 'MC_JAVA_OPERATOR_CONFUSION'
  | 'MC_JAVA_MISSING_SEMICOLON'
  | 'MC_JAVA_CASING_SYSTEM'
  | 'MC_JAVA_CASE_SENSITIVITY'
  | 'MC_JAVA_CODE_OUTSIDE_CLASS'
  | 'MC_JAVA_MISSING_MAIN'
  | 'MC_JAVA_SCANNER_BUFFER_SKIP'
  | 'MC_JAVA_INPUT_MISMATCH'
  | 'MC_JAVA_FORGOT_SCANNER_IMPORT'
  | 'MC_JAVA_QUOTES_ON_NUMBERS'
  | 'MC_JAVA_WRONG_DATA_TYPE'
  | 'MC_JAVA_ASSIGNMENT_VS_EQUALITY'
  | 'MC_JAVA_ASSIGNMENT_IN_CONDITION'
  | 'MC_JAVA_MISSING_BREAK'
  | 'MC_JAVA_MISSING_DEFAULT'
  | 'MC_JAVA_INFINITE_LOOP'
  | 'MC_JAVA_OFF_BY_ONE'
  | 'MC_JAVA_DIVIDE_BY_ZERO'
  | 'MC_JAVA_INTEGER_TRUNCATION'
  | 'MC_JAVA_OPERATOR_PRECEDENCE'
  | 'MC_JAVA_MODULO_REMAINDER'
  | 'MC_JAVA_MISSING_CURLY_BRACE'
  | 'MC_JAVA_VARIABLE_NOT_DECLARED'
  | 'MC_JAVA_BINARY_SEARCH_UNSORTED'
  | 'MC_JAVA_CONSTRUCTOR_NAME_MISMATCH'
  | 'MC_JAVA_DIRECT_PRIVATE_ACCESS'
  | 'MC_JAVA_INTERFACE_INSTANTIATION'
  | 'MC_JAVA_STATIC_ON_INSTANCE'
  | 'MC_JAVA_ARRAYLIST_INDEX_OUT_OF_BOUNDS'
  | 'MC_JAVA_HASHMAP_NULL_KEY'
  | 'MC_JAVA_THREAD_RUN_VS_START'
  | 'MC_JAVA_BOOLEAN_QUOTES'
  | 'MC_JAVA_IF_CONDITION_EXECUTION'
  | 'MC_JAVA_ELSE_BRANCH_LOGIC'
  | 'MC_JAVA_LOGICAL_AND_SHORT_CIRCUIT'
  | 'MC_JAVA_SWITCH_VS_IF_DISCRETE'
  | 'MC_JAVA_ACCUMULATOR_SCOPE'
  | 'MC_JAVA_NESTED_LOOP_MULTIPLICATION'
  | 'MC_JAVA_METHOD_PURPOSE_DRY'
  | 'MC_JAVA_METHOD_RETURN_TYPE_MISMATCH'
  | 'MC_JAVA_METHOD_CALL_COMPOSITION'
  | 'MC_JAVA_METHOD_RETURN_FEEDTHROUGH'
  | 'MC_JAVA_OVERLOAD_PURPOSE'
  | 'MC_JAVA_OVERLOAD_PARAMETER_SIGNATURE'
  | 'MC_JAVA_OVERLOAD_ARITY'
  | 'MC_JAVA_OVERLOAD_RETURN_TYPE_ONLY'
  | 'MC_JAVA_ARRAY_INDEX_PURPOSE'
  | 'MC_JAVA_FOREACH_COLON_SYNTAX'
  | 'MC_JAVA_FILTER_COUNT_LOGIC'
  | 'MC_JAVA_MATRIX_DIAGONAL_INDEX'
  | 'MC_JAVA_CLASS_VS_OBJECT'
  | 'MC_JAVA_NEW_KEYWORD_HEAP'
  | 'MC_JAVA_DOT_NOTATION_ACCESS'
  | 'MC_JAVA_CONSTRUCTOR_OVERLOADING'
  | 'MC_JAVA_INHERITANCE_CODE_REUSE'
  | 'MC_JAVA_EXTENDS_KEYWORD'
  | 'MC_JAVA_POLYMORPHISM_PARENT_REF'
  | 'MC_JAVA_DYNAMIC_METHOD_DISPATCH'
  | 'MC_JAVA_POLYMORPHIC_ARRAY'
  | 'MC_JAVA_INTERFACE_DECOUPLING'
  | 'MC_JAVA_FINALLY_GUARANTEED_RUN'
  | 'MC_JAVA_THROW_PURPOSE_HALT'
  | 'MC_JAVA_THROW_EXCEPTION_CONSTRUCTOR'
  | 'MC_JAVA_GUARD_CLAUSE_ORDER'
  | 'MC_JAVA_GENERICS_TYPE_SAFETY'
  | 'MC_JAVA_GENERIC_CLASS_TYPE_PARAM'
  | 'MC_JAVA_GENERIC_MULTI_TYPE_PARAMS'
  | 'MC_JAVA_STREAM_PIPELINE_MEMORY'
  | 'MC_JAVA_BUFFERED_READER_EOF_NULL'
  | 'MC_JAVA_TRY_WITH_RESOURCES_AUTOCLOSE'
  | 'MC_JAVA_CAPSTONE_SYSTEM_SYNTHESIS'
  | 'MC_JAVA_ENTITY_INVARIANT_VALIDATION'
  | 'MC_JAVA_AUDITOR_THRESHOLD_FILTER'
  | 'MC_JAVA_BALANCE_RECONCILIATION';

export type PythonMisconceptionId =
  | 'MC_PY_PRINT_CASE_SENSITIVITY'
  | 'MC_PY_EXECUTION_ORDER'
  | 'MC_PY_MISSING_QUOTES_STRING'
  | 'MC_PY_INDENTATION_SYNTAX'
  | 'MC_PY_INDENTATION_SCOPE_ERROR'
  | 'MC_PY_VARIABLE_REASSIGNMENT'
  | 'MC_PY_DYNAMIC_TYPE_MISMATCH'
  | 'MC_PY_INPUT_RETURNS_STR'
  | 'MC_PY_TYPE_CAST_VALUE_ERROR'
  | 'MC_PY_STR_INT_CONCAT_TYPE_ERROR'
  | 'MC_PY_INTEGER_DIVISION_SLASH'
  | 'MC_PY_MODULO_REMAINDER'
  | 'MC_PY_OPERATOR_PRECEDENCE'
  | 'MC_PY_ASSIGNMENT_VS_EQUALITY'
  | 'MC_PY_IF_CONDITION_TRUTHY'
  | 'MC_PY_ELSE_BRANCH_LOGIC'
  | 'MC_PY_LOGICAL_AND_SHORT_CIRCUIT'
  | 'MC_PY_ELIF_ORDER_PRECEDENCE'
  | 'MC_PY_WHILE_INFINITE_LOOP'
  | 'MC_PY_WHILE_SENTINEL_UPDATE'
  | 'MC_PY_RANGE_STOP_EXCLUSIVE'
  | 'MC_PY_RANGE_STEP_DIRECTION'
  | 'MC_PY_FOR_ACCUMULATOR_SCOPE'
  | 'MC_PY_NESTED_LOOP_COORDINATES'
  | 'MC_PY_FSTRING_EXPRESSION_EVAL'
  | 'MC_PY_FUNCTION_DEF_VS_CALL'
  | 'MC_PY_RETURN_VS_PRINT'
  | 'MC_PY_FUNCTION_PARAMETER_ORDER'
  | 'MC_PY_DEFAULT_PARAM_MUTABLE'
  | 'MC_PY_LOCAL_VS_GLOBAL_SCOPE'
  | 'MC_PY_UNBOUND_LOCAL_ERROR'
  | 'MC_PY_STACK_FRAME_LIFECYCLE'
  | 'MC_PY_LIST_ZERO_INDEX'
  | 'MC_PY_LIST_INDEX_OUT_OF_RANGE'
  | 'MC_PY_LIST_NEGATIVE_INDEXING'
  | 'MC_PY_LIST_SLICE_STOP_EXCLUSIVE'
  | 'MC_PY_LIST_ALIASING_MUTATION'
  | 'MC_PY_LIST_APPEND_RETURNS_NONE'
  | 'MC_PY_LIST_COMPREHENSION_SYNTAX'
  | 'MC_PY_TUPLE_IMMUTABILITY'
  | 'MC_PY_SET_UNIQUENESS'
  | 'MC_PY_DICT_KEY_ERROR'
  | 'MC_PY_DICT_GET_FALLBACK'
  | 'MC_PY_DICT_ITERATION_KEYS_VS_VALUES'
  | 'MC_PY_CLASS_VS_INSTANCE'
  | 'MC_PY_SELF_FIRST_PARAMETER'
  | 'MC_PY_INIT_CONSTRUCTOR_RETURN'
  | 'MC_PY_INSTANCE_ATTRIBUTE_LEAK'
  | 'MC_PY_PRIVATE_ATTRIBUTE_MANGLING'
  | 'MC_PY_PROPERTY_GETTER_SETTER'
  | 'MC_PY_INHERITANCE_SUPER_CALL'
  | 'MC_PY_METHOD_OVERRIDING_DISPATCH'
  | 'MC_PY_POLYMORPHIC_DUCK_TYPING'
  | 'MC_PY_MAGIC_METHOD_STR_REPR'
  | 'MC_PY_INTERFACE_PROTOCOL_CONTRACT'
  | 'MC_PY_DIVIDE_BY_ZERO'
  | 'MC_PY_TRY_EXCEPT_ORDER'
  | 'MC_PY_RAISE_EXCEPTION_TYPE'
  | 'MC_PY_FINALLY_ALWAYS_RUNS'
  | 'MC_PY_FILE_RESOURCE_LEAK_NO_WITH'
  | 'MC_PY_FILE_READLINE_STRIP_NEWLINE'
  | 'MC_PY_JSON_LOADS_VS_DUMPS'
  | 'MC_PY_DECORATOR_WRAPPER_RETURN'
  | 'MC_PY_LAMBDA_ONE_EXPRESSION'
  | 'MC_PY_ASYNC_AWAIT_UNRESOLVED_COROUTINE'
  | 'MC_PY_TYPE_HINT_RUNTIME_IGNORE'
  | 'MC_PY_FASTAPI_STATUS_CODE'
  | 'MC_PY_CAPSTONE_TRANSACTION_RECONCILER';

export type ReactMisconceptionId =
  | 'MC_REACT_JSX_VS_HTML'
  | 'MC_REACT_VIRTUAL_DOM_DIFFING'
  | 'MC_REACT_PROPS_IMMUTABILITY'
  | 'MC_REACT_PROPS_DESTRUCTURING'
  | 'MC_REACT_DIRECT_STATE_MUTATION'
  | 'MC_REACT_STATE_ASYNC_BATCHING'
  | 'MC_REACT_FUNCTIONAL_STATE_UPDATES'
  | 'MC_REACT_LIST_KEYS_INDEX_WARNING'
  | 'MC_REACT_CONDITIONAL_RENDERING_SHORT_CIRCUIT'
  | 'MC_REACT_EVENT_HANDLER_INVOCATION'
  | 'MC_REACT_SYNTHETIC_EVENT_POOLING'
  | 'MC_REACT_CONTROLLED_VS_UNCONTROLLED'
  | 'MC_REACT_FORM_PREVENT_DEFAULT'
  | 'MC_REACT_USE_EFFECT_RUN_TIMING'
  | 'MC_REACT_USE_EFFECT_DEPENDENCY_ARRAY'
  | 'MC_REACT_USE_EFFECT_INFINITE_LOOP'
  | 'MC_REACT_USE_EFFECT_CLEANUP_FN'
  | 'MC_REACT_STALE_CLOSURES'
  | 'MC_REACT_USE_REF_MUTATION_NO_RERENDER'
  | 'MC_REACT_USE_MEMO_PREMATURE_OPTIMIZATION'
  | 'MC_REACT_USE_CALLBACK_FUNCTION_IDENTITY'
  | 'MC_REACT_CONTEXT_VALUE_RECREATION'
  | 'MC_REACT_PROP_DRILLING_VS_CONTEXT'
  | 'MC_REACT_CUSTOM_HOOK_RULES'
  | 'MC_REACT_HOOK_CALLED_CONDITIONALLY'
  | 'MC_REACT_USE_REDUCER_ACTION_DISPATCH'
  | 'MC_REACT_COMPONENT_LIFECYCLE_UNMOUNT'
  | 'MC_REACT_ERROR_BOUNDARY_CATCH'
  | 'MC_REACT_LAZY_SUSPENSE_FALLBACK'
  | 'MC_REACT_PORTAL_DOM_ESCAPE'
  | 'MC_REACT_DERIVED_STATE_ANTI_PATTERN'
  | 'MC_REACT_SERVER_VS_CLIENT_COMPONENT'
  | 'MC_REACT_CAPSTONE_ECOMMERCE_STATE_ENGINE';

export type SqlMisconceptionId =
  | 'MC_SQL_NULL_EQUALITY_OPERATOR'
  | 'MC_SQL_COUNT_NULL_BEHAVIOR'
  | 'MC_SQL_WHERE_VS_HAVING'
  | 'MC_SQL_GROUP_BY_NON_AGGREGATE_COLUMN'
  | 'MC_SQL_INNER_VS_LEFT_JOIN'
  | 'MC_SQL_JOIN_ON_VS_WHERE'
  | 'MC_SQL_CROSS_JOIN_CARTESIAN_EXPLOSION'
  | 'MC_SQL_SUBQUERY_CORRELATED_PERFORMANCE'
  | 'MC_SQL_UNION_VS_UNION_ALL'
  | 'MC_SQL_ORDER_BY_EXECUTION_ORDER'
  | 'MC_SQL_LIMIT_OFFSET_PERFORMANCE'
  | 'MC_SQL_INDEX_LOOKUP_VS_FULL_TABLE_SCAN'
  | 'MC_SQL_COMPOSITE_INDEX_COLUMN_ORDER'
  | 'MC_SQL_TRANSACTION_ACID_ROLLBACK'
  | 'MC_SQL_ISOLATION_LEVEL_DIRTY_READ'
  | 'MC_SQL_PRIMARY_KEY_VS_UNIQUE_NULLS'
  | 'MC_SQL_FOREIGN_KEY_CASCADE_DELETE'
  | 'MC_SQL_CHECK_CONSTRAINT_VIOLATION'
  | 'MC_SQL_WINDOW_FUNCTION_OVER_PARTITION'
  | 'MC_SQL_ROW_NUMBER_VS_RANK_VS_DENSE_RANK'
  | 'MC_SQL_CTE_WITH_RECURSIVE'
  | 'MC_SQL_STRING_CASE_SENSITIVITY_LIKE'
  | 'MC_SQL_BETWEEN_BOUNDARY_INCLUSION'
  | 'MC_SQL_NORMALIZATION_REDUNDANCY'
  | 'MC_SQL_VIEW_MATERIALIZATION_OVERHEAD'
  | 'MC_SQL_CAPSTONE_LEDGER_RECONCILIATION';

export type DsaMisconceptionId =
  | 'MC_DSA_BIG_O_WORST_VS_AVERAGE'
  | 'MC_DSA_ARRAY_RESIZING_AMORTIZED_COST'
  | 'MC_DSA_LINKED_LIST_LOST_HEAD_POINTER'
  | 'MC_DSA_LINKED_LIST_CYCLE_DETECTION_FLOYD'
  | 'MC_DSA_STACK_UNDERFLOW_OVERFLOW'
  | 'MC_DSA_QUEUE_CIRCULAR_BUFFER_WRAP'
  | 'MC_DSA_HASH_COLLISION_CHAINING_LOAD_FACTOR'
  | 'MC_DSA_TWO_POINTER_OPPOSITE_VS_FAST_SLOW'
  | 'MC_DSA_SLIDING_WINDOW_FIXED_VS_DYNAMIC'
  | 'MC_DSA_BINARY_SEARCH_OFF_BY_ONE_MID'
  | 'MC_DSA_RECURSION_MISSING_BASE_CASE'
  | 'MC_DSA_DIVIDE_AND_CONQUER_MERGE_SORT_SPACE'
  | 'MC_DSA_QUICK_SORT_WORST_CASE_PIVOT'
  | 'MC_DSA_BINARY_TREE_INORDER_PREORDER_POSTORDER'
  | 'MC_DSA_BST_VALIDATION_MIN_MAX_BOUNDS'
  | 'MC_DSA_TREE_BALANCING_AVL_ROTATIONS'
  | 'MC_DSA_HEAP_MAX_MIN_PROPERTY_HEAPIFY'
  | 'MC_DSA_TRIE_PREFIX_NODE_END_OF_WORD'
  | 'MC_DSA_GRAPH_BFS_QUEUE_VISITED_SET'
  | 'MC_DSA_GRAPH_DFS_CYCLE_DETECTION_RECURSION'
  | 'MC_DSA_DIJKSTRA_SHORTEST_PATH_PRIORITY_QUEUE'
  | 'MC_DSA_TOPOLOGICAL_SORT_KAHN_INDEGREE'
  | 'MC_DSA_UNION_FIND_DISJOINT_SET_PATH_COMPRESSION'
  | 'MC_DSA_GREEDY_LOCAL_OPTIMUM_TRAP'
  | 'MC_DSA_DP_MEMOIZATION_VS_TABULATION'
  | 'MC_DSA_DP_01_KNAPSACK_STATE_TRANSITION'
  | 'MC_DSA_DP_LONGEST_COMMON_SUBSEQUENCE'
  | 'MC_DSA_BACKTRACKING_N_QUEENS_STATE_RESTORATION'
  | 'MC_DSA_BIT_MANIPULATION_XOR_TRICKS'
  | 'MC_DSA_CAPSTONE_GEO_ROUTING_NAVIGATION_ENGINE';

export type FullstackMisconceptionId =
  | 'MC_FS_CLIENT_VS_SERVER_EXECUTION_BOUNDARY'
  | 'MC_FS_EVENT_LOOP_BLOCKING_SYNC_CALLS'
  | 'MC_FS_EXPRESS_MIDDLEWARE_NEXT_OMISSION'
  | 'MC_FS_REST_HTTP_STATUS_CODE_MISUSE'
  | 'MC_FS_CORS_PREFLIGHT_OPTIONS_MISMATCH'
  | 'MC_FS_JWT_SIGNING_VS_ENCRYPTION_SECRET'
  | 'MC_FS_COOKIES_HTTPONLY_SAMESITE_FLAG'
  | 'MC_FS_SQL_INJECTION_PARAMETRIZED_QUERIES'
  | 'MC_FS_ORM_N_PLUS_ONE_QUERY_PROBLEM'
  | 'MC_FS_ENVIRONMENT_VARIABLES_LEAK_CLIENT'
  | 'MC_FS_STREAM_BUFFER_BACKPRESSURE_HANDLING'
  | 'MC_FS_WEBSOCKET_HANDSHAKE_VS_HTTP_POLLING'
  | 'MC_FS_REDIS_CACHE_STAMPEDE_TTL_EXPIRATION'
  | 'MC_FS_RATE_LIMITING_TOKEN_BUCKET_IP'
  | 'MC_FS_CSRF_TOKEN_VALIDATION_FAILURE'
  | 'MC_FS_FILE_UPLOAD_MULTIPART_STREAM_PARSING'
  | 'MC_FS_NEXTJS_SERVER_VS_CLIENT_COMPONENT'
  | 'MC_FS_NEXTJS_HYDRATION_MISMATCH_ERROR'
  | 'MC_FS_SSR_VS_SSG_VS_ISR_CACHE_CONTROL'
  | 'MC_FS_SERVER_ACTIONS_MUTATION_SECURITY'
  | 'MC_FS_ROUTE_HANDLER_RESPONSE_STREAMING'
  | 'MC_FS_MICROSERVICES_API_GATEWAY_ROUTING'
  | 'MC_FS_EVENT_DRIVEN_MESSAGE_BROKER_KAFKA'
  | 'MC_FS_DOCKER_CONTAINER_MULTI_STAGE_BUILD'
  | 'MC_FS_HEALTH_CHECK_LIVENESS_READINESS_PROBE'
  | 'MC_FS_GRAPHQL_SCHEMA_RESOLVER_OVERFETCH'
  | 'MC_FS_ZERO_DOWNTIME_BLUE_GREEN_DEPLOY'
  | 'MC_FS_OPENAPI_SWAGGER_CONTRACT_DRIFT'
  | 'MC_FS_CAPSTONE_ENTERPRISE_ECOMMERCE_PLATFORM';

export type CloudMisconceptionId =
  | 'MC_CLOUD_IAAS_PAAS_SAAS_SHARED_RESPONSIBILITY'
  | 'MC_CLOUD_REGION_VS_AZ_RESILIENCY_DISASTER'
  | 'MC_CLOUD_VPC_PUBLIC_VS_PRIVATE_SUBNET_NAT'
  | 'MC_CLOUD_SECURITY_GROUP_STATEFUL_VS_NACL_STATELESS'
  | 'MC_CLOUD_IAM_LEAST_PRIVILEGE_POLICY_ROLE'
  | 'MC_CLOUD_EC2_AUTO_SCALING_TARGET_TRACKING'
  | 'MC_CLOUD_ALB_PATH_ROUTING_HEALTH_PROBE'
  | 'MC_CLOUD_S3_STORAGE_CLASS_LIFECYCLE_TIERING'
  | 'MC_CLOUD_S3_BUCKET_POLICY_BLOCK_PUBLIC_ACCESS'
  | 'MC_CLOUD_SERVERLESS_LAMBDA_COLD_START_MEMORY'
  | 'MC_CLOUD_API_GATEWAY_THROTTLING_AUTHORIZER'
  | 'MC_CLOUD_DYNAMODB_PARTITION_KEY_HOTSPOTTING'
  | 'MC_CLOUD_RDS_MULTI_AZ_VS_READ_REPLICA'
  | 'MC_CLOUD_CLOUDFRONT_EDGE_CACHING_INVALIDATION'
  | 'MC_CLOUD_ROUTE53_FAILOVER_WEIGHTED_ROUTING'
  | 'MC_CLOUD_SQS_VISIBILITY_TIMEOUT_DEAD_LETTER'
  | 'MC_CLOUD_SNS_FANOUT_TOPIC_SUBSCRIPTION'
  | 'MC_CLOUD_EVENTBRIDGE_EVENT_BUS_SCHEMA_REGISTRY'
  | 'MC_CLOUD_STEP_FUNCTIONS_SAGA_STATE_MACHINE'
  | 'MC_CLOUD_ECS_FARGATE_CONTAINER_TASK_DEFINITION'
  | 'MC_CLOUD_EKS_KUBERNETES_MANAGED_NODE_GROUP'
  | 'MC_CLOUD_TERRAFORM_IAC_STATE_DRIFT_LOCKING'
  | 'MC_CLOUD_CLOUDWATCH_METRICS_LOGS_ALARMS'
  | 'MC_CLOUD_XRAY_DISTRIBUTED_TRACE_CONTEXT'
  | 'MC_CLOUD_KMS_ENCRYPTION_ENVELOPE_KEYS'
  | 'MC_CLOUD_WAF_SHIELD_DDOS_SQLI_RULESET'
  | 'MC_CLOUD_FINOPS_COST_OPTIMIZATION_SAVINGS_PLANS'
  | 'MC_CLOUD_DISASTER_RECOVERY_RTO_RPO_PILOT_LIGHT'
  | 'MC_CLOUD_MULTI_REGION_ACTIVE_ACTIVE_REPLICATION'
  | 'MC_CLOUD_CAPSTONE_GLOBAL_RESILIENT_FINTECH_INFRASTRUCTURE';

export type DevopsMisconceptionId =
  | 'MC_DEVOPS_12FACTOR_CONFIG_ENV_ISOLATION'
  | 'MC_DEVOPS_LINUX_SIGNALS_SIGTERM_SYSTEMD'
  | 'MC_DEVOPS_DOCKER_LAYER_CACHE_INVALIDATION'
  | 'MC_DEVOPS_DOCKER_MULTI_STAGE_IMAGE_SLIMMING'
  | 'MC_DEVOPS_DOCKER_COMPOSE_NETWORKING_DNS'
  | 'MC_DEVOPS_GITHUB_ACTIONS_WORKFLOW_SYNTAX'
  | 'MC_DEVOPS_CI_TEST_AUTOMATION_PARALLEL_MATRIX'
  | 'MC_DEVOPS_SEMANTIC_VERSIONING_GIT_TAGS'
  | 'MC_DEVOPS_CONTAINER_REGISTRY_IMAGE_SECURITY_SCAN'
  | 'MC_DEVOPS_K8S_POD_DEPLOYMENT_REPLICASET'
  | 'MC_DEVOPS_K8S_SERVICE_CLUSTERIP_NODEPORT_LOADBALANCER'
  | 'MC_DEVOPS_K8S_INGRESS_CONTROLLER_TLS'
  | 'MC_DEVOPS_K8S_CONFIGMAP_SECRET_VOLUME_MOUNT'
  | 'MC_DEVOPS_K8S_PROBES_LIVENESS_READINESS_STARTUP'
  | 'MC_DEVOPS_K8S_HPA_METRIC_SERVER_SCALING'
  | 'MC_DEVOPS_HELM_PACKAGE_TEMPLATING_VALUES'
  | 'MC_DEVOPS_ARGO_CD_GITOPS_DECLARATIVE_SYNC'
  | 'MC_DEVOPS_TERRAFORM_PLAN_APPLY_STATE_LOCK'
  | 'MC_DEVOPS_ANSIBLE_IDEMPOTENT_PLAYBOOK_ROLES'
  | 'MC_DEVOPS_PROMETHEUS_METRICS_PULL_SCRAPE'
  | 'MC_DEVOPS_GRAFANA_DASHBOARD_ALERT_PANEL'
  | 'MC_DEVOPS_ELK_LOGSTASH_FLUENTD_LOG_AGGREGATION'
  | 'MC_DEVOPS_JAEGER_OPENTELEMETRY_TRACE_SPAN'
  | 'MC_DEVOPS_BLUE_GREEN_TRAFFIC_CUTOVER'
  | 'MC_DEVOPS_CANARY_ROLLOUT_ANALYSIS_FLUID'
  | 'MC_DEVOPS_CHAOS_ENGINEERING_FAULT_INJECTION'
  | 'MC_DEVOPS_DEVSECOPS_SAST_DAST_SCA_SCANNING'
  | 'MC_DEVOPS_VAULT_DYNAMIC_SECRET_MANAGEMENT'
  | 'MC_DEVOPS_ZERO_DOWNTIME_DB_SCHEMA_MIGRATION'
  | 'MC_DEVOPS_CAPSTONE_ENTERPRISE_GITOPS_K8S_CICD_PLATFORM';

export type AiMisconceptionId =
  | 'MC_AI_TRANSFORMER_SELF_ATTENTION_QUERY_KEY_VALUE'
  | 'MC_AI_TOKENIZATION_BPE_BYTE_PAIR_ENCODING'
  | 'MC_AI_SYSTEM_PROMPTS_ROLE_PERSONA_GUARDRAILS'
  | 'MC_AI_FEW_SHOT_CHAIN_OF_THOUGHT_PROMPTING'
  | 'MC_AI_STRUCTURED_OUTPUTS_JSON_SCHEMA_ENFORCEMENT'
  | 'MC_AI_FUNCTION_CALLING_TOOL_DECLARATION'
  | 'MC_AI_EMBEDDINGS_VECTOR_SIMILARITY_COSINE'
  | 'MC_AI_VECTOR_DB_CHROMA_PINECONE_INDEXING'
  | 'MC_AI_CHUNK_STRATEGY_OVERLAP_RECURSIVE_SPLIT'
  | 'MC_AI_RAG_NAIVE_VS_HYBRID_SEARCH_BM25'
  | 'MC_AI_RAG_RERANKING_CROSS_ENCODER_COHERE'
  | 'MC_AI_RAG_CONTEXT_COMPRESSION_LOST_IN_MIDDLE'
  | 'MC_AI_RAG_EVALUATION_RAGAS_TRULENS_FAITHFULNESS'
  | 'MC_AI_GUARDRAILS_PROMPT_INJECTION_JAILBREAK_DEFENSE'
  | 'MC_AI_LLM_MEMORY_SLIDING_WINDOW_SUMMARY_BUFFER'
  | 'MC_AI_AUTONOMOUS_AGENTS_REACT_REASON_ACT'
  | 'MC_AI_MULTI_AGENT_SUPERVISOR_CREWAI_AUTOGEN'
  | 'MC_AI_AGENTIC_WORKFLOWS_PLAN_AND_SOLVE'
  | 'MC_AI_STREAMING_SSE_CHUNK_TOKEN_PIPELINE'
  | 'MC_AI_LLM_CACHING_EXACT_SEMANTIC_REDIS'
  | 'MC_AI_FINE_TUNING_LORA_QLORA_ADAPTERS'
  | 'MC_AI_DPO_RLHF_PREFERENCE_ALIGNMENT'
  | 'MC_AI_OPEN_SOURCE_LLMS_VLLM_OLLAMA_QUANTIZATION'
  | 'MC_AI_MULTIMODAL_VISION_AUDIO_EMBEDDINGS'
  | 'MC_AI_LLM_RATE_LIMITING_TOKEN_BUCKET_TIERS'
  | 'MC_AI_LLM_OBSERVABILITY_TRACING_LANGFUSE_HELICONE'
  | 'MC_AI_AI_SAFETY_HALLUCINATION_GROUNDING_CHECKS'
  | 'MC_AI_CODE_GENERATION_SANDBOX_E2B_SECURITY'
  | 'MC_AI_GRAPH_RAG_KNOWLEDGE_GRAPHS_NEO4J'
  | 'MC_AI_CAPSTONE_ENTERPRISE_AGENTIC_RAG_ASSISTANT';

export type DistributedMisconceptionId =
  | 'MC_DIST_FALLACIES_NETWORK_RELIABILITY_LATENCY'
  | 'MC_DIST_CAP_PACELC_CONSISTENCY_AVAILABILITY'
  | 'MC_DIST_RPC_PROTOBUF_SERIALIZATION_MULTIPLEXING'
  | 'MC_DIST_CONSISTENT_HASHING_VIRTUAL_NODES'
  | 'MC_DIST_DISTRIBUTED_CACHING_WRITE_THROUGH_CACHE_ASIDE'
  | 'MC_DIST_CACHE_INVALIDATION_STAMPEDE_THUNDERING_HERD'
  | 'MC_DIST_DISTRIBUTED_LOCKS_REDLOCK_TTL_LEASE'
  | 'MC_DIST_LEADER_ELECTION_BULLY_RING_RAFT'
  | 'MC_DIST_CONSENSUS_RAFT_LOG_REPLICATION_HEARTBEATS'
  | 'MC_DIST_PAXOS_TWO_PHASE_COMMIT_2PC_3PC'
  | 'MC_DIST_SAGA_PATTERN_COMPENSATING_TRANSACTIONS'
  | 'MC_DIST_EVENT_DRIVEN_KAFKA_PARTITIONS_CONSUMER_GROUPS'
  | 'MC_DIST_MESSAGE_DELIVERY_EXACTLY_ONCE_IDEMPOTENCY'
  | 'MC_DIST_CIRCUIT_BREAKER_BULKHEAD_RESILIENCE'
  | 'MC_DIST_RATE_LIMITING_TOKEN_LEAKY_BUCKET_SLIDING_LOG'
  | 'MC_DIST_VECTOR_CLOCKS_LAMPORT_TIMESTAMPS_CAUSALITY'
  | 'MC_DIST_CRDT_CONFLICT_FREE_REPLICATED_DATA_TYPES'
  | 'MC_DIST_DATABASE_SHARDING_RANGE_HASH_DIRECTORY'
  | 'MC_DIST_READ_REPLICAS_REPLICATION_LAG_READ_YOUR_WRITES'
  | 'MC_DIST_GOSSIP_PROTOCOL_FAILURE_DETECTION_SWIM'
  | 'MC_DIST_LOAD_BALANCING_LEAST_CONNECTIONS_ROUND_ROBIN'
  | 'MC_DIST_SERVICE_DISCOVERY_CONSUL_ZOOKEEPER_HEARTBEATS'
  | 'MC_DIST_API_GATEWAY_BFF_BACKEND_FOR_FRONTEND'
  | 'MC_DIST_DISTRIBUTED_TRACING_OPENTELEMETRY_TRACEPARENT'
  | 'MC_DIST_DEAD_LETTER_QUEUES_POISON_PILL_RETRY_BACKOFF'
  | 'MC_DIST_DATA_CONSISTENCY_EVENTUAL_READ_COMMITTED_LINEARIZABLE'
  | 'MC_DIST_REVERSE_PROXY_CDN_EDGE_CACHING_PURGE'
  | 'MC_DIST_DISTRIBUTED_UNIQUE_ID_SNOWFLAKE_ULID'
  | 'MC_DIST_DISASTER_RECOVERY_MULTI_REGION_ACTIVE_ACTIVE'
  | 'MC_DIST_CAPSTONE_ENTERPRISE_GLOBAL_FINTECH_EXCHANGE_PLATFORM';

export type IotEmbeddedMisconceptionId =
  | 'MC_IOT_ARCH_HARVARD_VON_NEUMANN_FLASH_SRAM'
  | 'MC_IOT_GPIO_MODES_PULLUP_PULLDOWN_FLOATING'
  | 'MC_IOT_DEBOUNCING_SWITCH_BOUNCE_RC_SOFTWARE'
  | 'MC_IOT_ADC_RESOLUTION_SAMPLING_QUANTIZATION'
  | 'MC_IOT_PWM_DUTY_CYCLE_FREQUENCY_TIMER'
  | 'MC_IOT_INTERRUPTS_ISR_VOLATILE_CRITICAL_SECTION'
  | 'MC_IOT_TIMERS_WATCHDOG_WDT_PRESCALER'
  | 'MC_IOT_UART_BAUD_RATE_PARITY_FRAMING'
  | 'MC_IOT_I2C_ADDRESSING_ACK_NACK_PULLUPS'
  | 'MC_IOT_SPI_CPOL_CPHA_FULL_DUPLEX'
  | 'MC_IOT_RTOS_TASKS_PREEMPTION_PRIORITY_INVERSION'
  | 'MC_IOT_SEMAPHORES_MUTEX_QUEUE_DEADLOCK'
  | 'MC_IOT_MEMORY_ALIGNMENT_DMA_CIRCULAR_BUFFER'
  | 'MC_IOT_POWER_MANAGEMENT_DEEP_SLEEP_WAKEUP'
  | 'MC_IOT_MQTT_TOPICS_QOS_RETAIN_WILL'
  | 'MC_IOT_COAP_REST_UDP_CONFIRMABLE'
  | 'MC_IOT_BLE_GATT_SERVICES_CHARACTERISTICS_NOTIFY'
  | 'MC_IOT_SENSORS_CALIBRATION_NOISE_KALMAN_FILTER'
  | 'MC_IOT_ACTUATORS_SERVO_STEPPER_H_BRIDGE'
  | 'MC_IOT_STORAGE_EEPROM_FLASH_WEAR_LEVELING'
  | 'MC_IOT_OTA_DUAL_BANK_ROLLBACK_SECURE_BOOT'
  | 'MC_IOT_SECURITY_HARDWARE_ROOT_OF_TRUST_CRYPTO'
  | 'MC_IOT_CAN_BUS_ARBITRATION_DIFFERENTIAL_FRAMING'
  | 'MC_IOT_CELLULAR_NBIOT_LTE_M_POWER_SAVING'
  | 'MC_IOT_LORAWAN_SPREADING_FACTOR_DUTY_CYCLE'
  | 'MC_IOT_EDGE_TINYML_QUANTIZATION_INT8_DSP'
  | 'MC_IOT_DIAGNOSTICS_SWD_JTAG_LOGIC_ANALYZER'
  | 'MC_IOT_DEVICE_TWINS_SHADOW_STATE_DELTA'
  | 'MC_IOT_FLEET_MANAGEMENT_TELEMETRY_ANOMALY'
  | 'MC_IOT_CAPSTONE_AUTONOMOUS_SMART_FACTORY_ROBOTICS';

export type Graphics3dMisconceptionId =
  | 'MC_3D_PIPELINE_SPACES_LOCAL_WORLD_VIEW_CLIP'
  | 'MC_3D_WEBGL_CONTEXT_VIEWPORT_BUFFER_SWAP'
  | 'MC_3D_LINEAR_ALGEBRA_DOT_CROSS_NORMALIZATION'
  | 'MC_3D_TRANSFORMATION_MATRICES_TRANSLATE_ROTATE_SCALE'
  | 'MC_3D_PERSPECTIVE_PROJECTION_FOV_FRUSTUM_ASPECT'
  | 'MC_3D_SHADERS_GLSL_VERTEX_FRAGMENT_VARYING'
  | 'MC_3D_LIGHTING_PHONG_BLINN_AMBIENT_DIFFUSE_SPECULAR'
  | 'MC_3D_PBR_COOK_TORRANCE_METALLIC_ROUGHNESS_ALBEDO'
  | 'MC_3D_TEXTURE_MAPPING_UV_WRAPPING_MIPMAPPING_SAMPLER'
  | 'MC_3D_NORMAL_MAPPING_TBN_TANGENT_SPACE'
  | 'MC_3D_CAMERA_CONTROLS_ORBIT_QUATERNION_GIMBAL_LOCK'
  | 'MC_3D_SHADOW_MAPPING_DEPTH_FRAMEBUFFER_PCF'
  | 'MC_3D_POST_PROCESSING_BLOOM_TONEMAPPING_HDR'
  | 'MC_3D_GEOMETRY_INDEXED_VAO_VBO_DRAW_ELEMENTS'
  | 'MC_3D_GLTF_SCENE_GRAPH_NODES_HIERARCHY'
  | 'MC_3D_SKELETAL_RIGGING_BONES_JOINTS_MATRICES'
  | 'MC_3D_SKINNING_VERTEX_WEIGHTS_INVERSE_BIND_POSE'
  | 'MC_3D_FORWARD_INVERSE_KINEMATICS_FABRIK_CCD'
  | 'MC_3D_ANIMATION_CLIPS_KEYFRAMES_SLERP_LERP'
  | 'MC_3D_ANIMATION_BLENDING_CROSSFADE_STATE_MACHINE'
  | 'MC_3D_FACIAL_RIGGING_MORPH_TARGETS_BLENDSHAPES'
  | 'MC_3D_LIP_SYNC_VISEMES_AUDIO_AMPLITUDE_SPECTROGRAM'
  | 'MC_3D_PHYSICS_COLLISION_RAYCASTING_AABB_OBB'
  | 'MC_3D_CLOTH_HAIR_VERLET_INTEGRATION_CONSTRAINTS'
  | 'MC_3D_PARTICLE_SYSTEMS_GPU_INSTANCING_BILLBOARD'
  | 'MC_3D_OPTIMIZATION_LOD_OCCLUSION_CULLING_DRAW_CALLS'
  | 'MC_3D_WEBXR_VR_AR_HEADSET_POSE_SPATIAL_TRACKING'
  | 'MC_3D_PROCEDURAL_GENERATION_NOISE_TERRAIN_MESH'
  | 'MC_3D_SHADOW_VOLUMES_SSAO_AMBIENT_OCCLUSION'
  | 'MC_3D_CAPSTONE_AVATAR_CINEMATIC_METAVERSE_ENGINE';

export type BlockchainMisconceptionId =
  | 'MC_CHAIN_IMMUTABLE_HASH_POINTER_BLOCK_TAMPERING'
  | 'MC_CHAIN_MERKLE_TREE_ROOT_PROOF_VERIFICATION'
  | 'MC_CHAIN_ASYMMETRIC_SECP256K1_KEYPAIR_ADDRESS_DERIVATION'
  | 'MC_CHAIN_CONSENSUS_PROOF_OF_WORK_DIFFICULTY_NONCE'
  | 'MC_CHAIN_CONSENSUS_PROOF_OF_STAKE_SLASHING_VALIDATOR'
  | 'MC_CHAIN_UTXO_VS_ACCOUNT_BASED_STATE_MODELS'
  | 'MC_CHAIN_EVM_ARCHITECTURE_OPCODES_STACK_MEMORY_STORAGE'
  | 'MC_CHAIN_SOLIDITY_TYPES_MAPPINGS_ARRAYS_STRUCTS'
  | 'MC_CHAIN_SOLIDITY_FUNCTIONS_VIEW_PURE_PAYABLE_FALLBACK'
  | 'MC_CHAIN_SOLIDITY_EVENTS_LOGS_INDEXED_TOPICS'
  | 'MC_CHAIN_SOLIDITY_STORAGE_SLOTS_PACKING_GAS'
  | 'MC_CHAIN_ERC20_TOKEN_STANDARD_ALLOWANCE_TRANSFERFROM'
  | 'MC_CHAIN_ERC721_ERC1155_NFT_TOKEN_URI_ROYALTIES'
  | 'MC_CHAIN_REENTRANCY_ATTACK_CHECKS_EFFECTS_INTERACTIONS'
  | 'MC_CHAIN_ACCESS_CONTROL_OWNABLE_ROLES_TIMELOCK'
  | 'MC_CHAIN_DEFI_AUTOMATED_MARKET_MAKER_CONSTANT_PRODUCT_AMM'
  | 'MC_CHAIN_DEFI_FLASH_LOANS_ATOMIC_ARBITRAGE'
  | 'MC_CHAIN_DEFI_STAKING_YIELD_FARMING_REWARD_RATES'
  | 'MC_CHAIN_ORACLES_CHAINLINK_PRICE_FEEDS_VRF'
  | 'MC_CHAIN_UPGRADEABLE_CONTRACTS_PROXY_DELEGATECALL_UUPS'
  | 'MC_CHAIN_GAS_OPTIMIZATION_CALLLIGHT_CUSTOM_ERRORS'
  | 'MC_CHAIN_ETHERS_VIEM_JSON_RPC_PROVIDER_SIGNER'
  | 'MC_CHAIN_TRANSACTION_GAS_ESTIMATION_EIP1559_NONCE'
  | 'MC_CHAIN_EVENT_INDEXING_GRAPH_PROTOCOL_SUBGRAPHS'
  | 'MC_CHAIN_IPFS_DECENTRALIZED_STORAGE_CID_PINNING'
  | 'MC_CHAIN_LAYER2_ROLLUPS_OPTIMISTIC_FRAUD_PROOF_ZK_SNARK'
  | 'MC_CHAIN_ACCOUNT_ABSTRACTION_ERC4337_BUNDLER_PAYMASTER'
  | 'MC_CHAIN_CROSS_CHAIN_BRIDGES_MESSAGE_PASSING'
  | 'MC_CHAIN_GOVERNANCE_DAOS_VOTING_QUORUM_PROPOSALS'
  | 'MC_CHAIN_CAPSTONE_ENTERPRISE_DEFI_DEX_STAKING_ECOSYSTEM';

export type IotNetworkMisconceptionId =
  | 'MC_IOTNET_SPECTRUM_SUBGHZ_VS_2_4GHZ_PROPAGATION'
  | 'MC_IOTNET_WIFI_LWIP_TCP_SOCKET_BUFFER_EXHAUSTION'
  | 'MC_IOTNET_BLE_ADVERTISING_PDU_BEACON_PAYLOADS'
  | 'MC_IOTNET_BLE_GATT_SERVICES_CHARACTERISTICS_NOTIFY'
  | 'MC_IOTNET_BLE_MESH_FLOODING_RELAY_NODES'
  | 'MC_IOTNET_ZIGBEE_802154_PAN_COORDINATOR_ROUTER'
  | 'MC_IOTNET_THREAD_IP6_BORDER_ROUTER_COAP'
  | 'MC_IOTNET_LORAWAN_SPREADING_FACTOR_AIRTIME_REGULATION'
  | 'MC_IOTNET_LORAWAN_OTAA_VS_ABP_SESSION_KEYS'
  | 'MC_IOTNET_LORAWAN_CLASS_A_B_C_UPLINK_DOWNLINK'
  | 'MC_IOTNET_NBIOT_LTE_M_E_DRX_PSM_BATTERY_LIFECYCLE'
  | 'MC_IOTNET_SATELLITE_IOT_DORBIT_PROPAGATION_LINK_BUDGET'
  | 'MC_IOTNET_COAP_UDP_RESTFUL_CONFIRMABLE_CON_NON'
  | 'MC_IOTNET_MQTT_SN_UDP_GATEWAY_CLIENTID_REGISTRATION'
  | 'MC_IOTNET_CBOR_MESSAGEPACK_BINARY_SERIALIZATION'
  | 'MC_IOTNET_DTLS_PSK_CERTIFICATES_HANDSHAKE_OVERHEAD'
  | 'MC_IOTNET_6LOWPAN_IPV6_HEADER_COMPRESSION_LOWPAN_IPHC'
  | 'MC_IOTNET_RPL_ROUTING_DODAG_OBJECTIVE_FUNCTIONS'
  | 'MC_IOTNET_NETWORK_TIME_SYNC_SNTP_TSCH_SLOTTED_MAC'
  | 'MC_IOTNET_GATEWAY_ARCHITECTURE_PACKET_FORWARDER'
  | 'MC_IOTNET_EDGE_COMMUNICATION_FAILOVER_HEARTBEATS'
  | 'MC_IOTNET_ANTENNA_RF_MATCHING_VSWR_PATH_LOSS'
  | 'MC_IOTNET_CELLULAR_AT_COMMANDS_PARSER_STATE_MACHINE'
  | 'MC_IOTNET_QOS_BANDWIDTH_ENERGY_TRADE_OFF_ANALYSIS'
  | 'MC_IOTNET_RADIO_JAMMING_REPLAY_ATTACK_DEFENSES'
  | 'MC_IOTNET_MESH_SELF_HEALING_TOPOLOGY_DISCOVERY'
  | 'MC_IOTNET_ROAMING_MULTICAST_FIRMWARE_OTA_FUOTA'
  | 'MC_IOTNET_ENERGY_HARVESTING_DUTY_CYCLING_OPTIMIZATION'
  | 'MC_IOTNET_TELECOMMUNICATION_REGULATORY_DUTY_LIMITS'
  | 'MC_IOTNET_CAPSTONE_SMART_CITY_MULTI_RADIO_ORCHESTRATION';

export type IotEdgeAiMisconceptionId =
  | 'MC_EDGEAI_ON_DEVICE_LATENCY_VS_CLOUD_OFFLOADING'
  | 'MC_EDGEAI_MCU_RAM_FLASH_MEMORY_BUDGETING'
  | 'MC_EDGEAI_TFLM_TENSOR_ARENA_ALLOCATION'
  | 'MC_EDGEAI_POST_TRAINING_QUANTIZATION_INT8_SYMMETRIC'
  | 'MC_EDGEAI_FLOAT32_TO_INT8_SCALE_ZERO_POINT'
  | 'MC_EDGEAI_DSP_NYQUIST_SAMPLING_ALIASING'
  | 'MC_EDGEAI_DSP_FFT_SPECTROGRAM_FEATURE_EXTRACTION'
  | 'MC_EDGEAI_MFCC_AUDIO_SPECTROGRAM_PREPROCESSING'
  | 'MC_EDGEAI_VIBRATION_ANOMALY_MAHALANOBIS_DISTANCE'
  | 'MC_EDGEAI_ACCELEROMETER_GESTURE_CNN_INFERENCE'
  | 'MC_EDGEAI_CMSIS_NN_SIMD_OPTIMIZATION_DSP_INSTRUCTIONS'
  | 'MC_EDGEAI_PRUNING_SPARSITY_WEIGHT_COMPRESSION'
  | 'MC_EDGEAI_DEPTHWISE_SEPARABLE_CONVOLUTION_PARAMS'
  | 'MC_EDGEAI_PERSON_DETECTION_VISUAL_WAKE_WORDS'
  | 'MC_EDGEAI_KWS_KEYWORD_SPOTTING_WAKE_WORD_MODEL'
  | 'MC_EDGEAI_ONNX_TO_TFLITE_MICRO_CONVERSION'
  | 'MC_EDGEAI_ENERGY_PER_INFERENCE_MILLIJOULES'
  | 'MC_EDGEAI_NPU_HARDWARE_ACCELERATOR_OFFLOAD'
  | 'MC_EDGEAI_CONTINUOUS_STREAMING_CIRCULAR_BUFFER'
  | 'MC_EDGEAI_CONFIDENCE_THRESHOLD_HYSTERESIS'
  | 'MC_EDGEAI_EDGE_ANOMALY_AUTOENCODER_RECONSTRUCTION_LOSS'
  | 'MC_EDGEAI_KALMAN_FILTER_SENSOR_FUSION_PREDICTION'
  | 'MC_EDGEAI_TEMPERATURE_COMPENSATION_DRIFT_FILTER'
  | 'MC_EDGEAI_TINIEST_LLM_TRANSFORMER_EDGE_QUANTIZATION'
  | 'MC_EDGEAI_ZERO_COPY_DMA_TO_INFERENCE_PIPELINE'
  | 'MC_EDGEAI_ADVERSARIAL_ROBUSTNESS_SENSOR_SPOOFING'
  | 'MC_EDGEAI_CONTINUAL_LEARNING_ON_DEVICE_FEW_SHOT'
  | 'MC_EDGEAI_MULTI_MODEL_CONCURRENT_TENSOR_ARENA'
  | 'MC_EDGEAI_FAIL_SAFE_HEURISTIC_BACKUP_CIRCUITS'
  | 'MC_EDGEAI_CAPSTONE_PREDICTIVE_MAINTENANCE_VISION_AUDIO_FUSION';

export type IotSecurityMisconceptionId =
  | 'MC_IOTSEC_HARDWARE_ROOT_OF_TRUST_BOOT_ROM'
  | 'MC_IOTSEC_AES_CBC_CTR_GCM_BLOCK_IV_PADDING'
  | 'MC_IOTSEC_ECC_ECDSA_PUBLIC_KEY_SIGNATURE_VERIFICATION'
  | 'MC_IOTSEC_ANTI_ROLLBACK_MONOTONIC_EFUSE_COUNTERS'
  | 'MC_IOTSEC_DEVICE_PROVISIONING_X509_CERT_CHAIN'
  | 'MC_IOTSEC_SECURE_ELEMENT_TPM_CRYPTO_OFFLOAD'
  | 'MC_IOTSEC_JTAG_SWD_DEBUG_PORT_FUSING_LOCKOUT'
  | 'MC_IOTSEC_FLASH_ENCRYPTION_AES_XTS_BUS_SCRAMBLING'
  | 'MC_IOTSEC_SECURE_OTA_IMAGE_HEADER_HMAC_PARSING'
  | 'MC_IOTSEC_FIRMWARE_DELTA_PATCH_INTEGRITY_CHECK'
  | 'MC_IOTSEC_ZERO_TOUCH_PROVISIONING_EST_ENROLLMENT'
  | 'MC_IOTSEC_CERT_REVOCATION_CRL_OCSP_STAPLING'
  | 'MC_IOTSEC_TLS_DTLS_CIPHER_SUITE_NEGOTIATION'
  | 'MC_IOTSEC_TRUSTZONE_MEMORY_ISOLATION_FAULT'
  | 'MC_IOTSEC_SIDE_CHANNEL_POWER_ANALYSIS_DPA_SHIELD'
  | 'MC_IOTSEC_GLITCH_FAULT_INJECTION_CLOCK_BROWNOUT'
  | 'MC_IOTSEC_PHYSICALLY_UNCLONABLE_FUNCTIONS_PUF_SRAM'
  | 'MC_IOTSEC_MUTUAL_TLS_MTLS_DEVICE_IDENTITY_AUTHENTICATION'
  | 'MC_IOTSEC_SECURE_STORAGE_KEYRING_ATTESTATION'
  | 'MC_IOTSEC_SEVERITY_CVSS_CVE_VULNERABILITY_TRIAGE'
  | 'MC_IOTSEC_FIRMWARE_SBOOM_SOFTWARE_BILL_OF_MATERIALS'
  | 'MC_IOTSEC_MEMORY_CORRUPTION_CANARY_STACK_OVERFLOW'
  | 'MC_IOTSEC_CAN_BUS_VEHICLE_INTRUSION_DETECTION_IDS'
  | 'MC_IOTSEC_MODBUS_PROFINET_INDUSTRIAL_FIREWALL_RULES'
  | 'MC_IOTSEC_SECURE_COMMISSIONING_BLE_OOB_PASE'
  | 'MC_IOTSEC_DECOMMISSIONING_CRYPTO_ERASE_FACTORY_RESET'
  | 'MC_IOTSEC_SECURE_LOGGING_WRITE_ONCE_APPEND_ONLY'
  | 'MC_IOTSEC_REMOTE_ATTESTATION_DICE_RIoT_MEASUREMENT'
  | 'MC_IOTSEC_INCIDENT_ISOLATION_QUARANTINE_HEURISTICS'
  | 'MC_IOTSEC_CAPSTONE_INDUSTRIAL_ZERO_TRUST_FLEET_SECURITY';

export type QuantMisconceptionId =
  | 'MC_QUANT_MARKET_MICROSTRUCTURE_ORDER_TYPES'
  | 'MC_QUANT_LIMIT_ORDER_BOOK_FIFO_PRICE_TIME_PRIORITY'
  | 'MC_QUANT_MATCHING_ENGINE_PARTIAL_FILLS_CANCELLATION'
  | 'MC_QUANT_VWAP_TWAP_EXECUTION_ALGORITHMS'
  | 'MC_QUANT_MARKET_IMPACT_AND_SLIPPAGE_MODELS'
  | 'MC_QUANT_ORDER_BOOK_IMBALANCE_AND_MICRO_PRICE'
  | 'MC_QUANT_STATISTICAL_ARBITRAGE_COINTEGRATION_PAIRS'
  | 'MC_QUANT_MARKET_MAKING_AVEM_STOIKOV_SPREAD'
  | 'MC_QUANT_FIX_PROTOCOL_TAGVALUE_ENCODING'
  | 'MC_QUANT_ITCH_OUCH_BINARY_EXCHANGE_FEEDS'
  | 'MC_QUANT_KERNEL_BYPASS_DPDK_SOLARFLARE_ONLOAD'
  | 'MC_QUANT_RING_BUFFER_LOCK_FREE_SPSC_QUEUE'
  | 'MC_QUANT_CPU_CACHE_ALIGNMENT_FALSE_SHARING'
  | 'MC_QUANT_SIMD_AVX512_VECTORIZED_PRICING'
  | 'MC_QUANT_ZERO_ALLOCATION_GARBAGE_COLLECTION_FREE'
  | 'MC_QUANT_OPTION_PRICING_BLACK_SCHOLES_GREEKS'
  | 'MC_QUANT_IMPLIED_VOLATILITY_SURFACE_NEWTON_RAPHSON'
  | 'MC_QUANT_VALUE_AT_RISK_VAR_HISTORICAL_PARAMETRIC'
  | 'MC_QUANT_EXPECTED_SHORTFALL_CVAR_TAIL_RISK'
  | 'MC_QUANT_PORTFOLIO_OPTIMIZATION_MARKOWITZ_FRONTIER'
  | 'MC_QUANT_HIGH_FREQUENCY_ALPHA_SIGNAL_EXTRACTION'
  | 'MC_QUANT_ORDER_ROUTING_SMART_SOR_BEST_EXECUTION'
  | 'MC_QUANT_EXCHANGE_COLOCATION_CROSS_CONNECT_PHYSICS'
  | 'MC_QUANT_MICROWAVE_FIBER_SPEED_OF_LIGHT_LATENCY'
  | 'MC_QUANT_BACKTESTING_LOOKAHEAD_BIAS_OVERFITTING'
  | 'MC_QUANT_SURVIVORSHIP_BIAS_CORPORATE_ACTIONS'
  | 'MC_QUANT_RISK_LIMITS_FAT_FINGER_CIRCUIT_BREAKERS'
  | 'MC_QUANT_REGULATORY_REG_NMS_RULE_611_TRADE_THROUGH'
  | 'MC_QUANT_CRYPTO_PERPETUAL_FUTURES_FUNDING_RATE'
  | 'MC_QUANT_CAPSTONE_ULTRA_LOW_LATENCY_TRADING_ECOSYSTEM';

export type BcomAccountingMisconceptionId =
  | 'MC_ACC_DOUBLE_ENTRY_EQUATION_ASSETS_EQUALS_LIABILITIES_EQUITY'
  | 'MC_ACC_THREE_GOLDEN_RULES_DEBIT_CREDIT_CLASSIFICATION'
  | 'MC_ACC_JOURNALIZING_COMPOUND_ENTRIES_BALANCING'
  | 'MC_ACC_LEDGER_POSTING_AND_CLOSING_BALANCES'
  | 'MC_ACC_THREE_COLUMN_CASH_BOOK_CONTRA_ENTRIES'
  | 'MC_ACC_BANK_RECONCILIATION_STATEMENT_BRS_TIMING_DIFFERENCES'
  | 'MC_ACC_RECTIFICATION_OF_ERRORS_SUSPENSE_ACCOUNT'
  | 'MC_ACC_DEPRECIATION_SLM_VS_WDV_CALCULATION'
  | 'MC_ACC_TRIAL_BALANCE_CHECKSUM_AND_LIMITATIONS'
  | 'MC_ACC_FINAL_ACCOUNTS_TRADING_AND_PROFIT_LOSS'
  | 'MC_ACC_BALANCE_SHEET_LIQUIDITY_PERMANENCE_ORDER'
  | 'MC_ACC_TALLY_PRIME_ERP_MASTERS_AND_VOUCHERS'
  | 'MC_ACC_GST_DUAL_STRUCTURE_CGST_SGST_IGST'
  | 'MC_ACC_INPUT_TAX_CREDIT_ITC_CROSS_UTILIZATION_ORDER'
  | 'MC_ACC_GSTR1_GSTR3B_RETURN_FILING_AND_RECONCILIATION'
  | 'MC_ACC_REVERSE_CHARGE_MECHANISM_RCM_LIABILITY'
  | 'MC_ACC_EWAY_BILL_GENERATION_AND_DISTANCE_RULES'
  | 'MC_ACC_PAYROLL_STATUTORY_DEDUCTIONS_EPF_ESI_PT'
  | 'MC_ACC_TDS_COMPLIANCE_SECTIONS_194C_194J_194I'
  | 'MC_ACC_INCOME_TAX_OLD_VS_NEW_REGIME_SECTION_115BAC'
  | 'MC_ACC_CAPITAL_GAINS_INDEXATION_AND_TAX_COMPUTATION'
  | 'MC_ACC_CORPORATE_TAX_SECTION_115BAA_EFFECTIVE_RATE'
  | 'MC_ACC_FINANCIAL_RATIO_ANALYSIS_LIQUIDITY_PROFITABILITY'
  | 'MC_ACC_CASH_FLOW_STATEMENT_AS3_OPERATING_INVESTING_FINANCING'
  | 'MC_ACC_WORKING_CAPITAL_CYCLE_MANAGEMENT'
  | 'MC_ACC_INTERNAL_FINANCIAL_CONTROLS_AND_AUDIT_TRAILS'
  | 'MC_ACC_IND_AS_IFRS_CONVERGENCE_STANDARDS'
  | 'MC_ACC_CLOUD_AI_AUTOMATED_INVOICE_PROCESSING_OCR'
  | 'MC_ACC_FRAUD_DETECTION_FORENSIC_ACCOUNTING_BENFORD'
  | 'MC_ACC_CAPSTONE_CORPORATE_ACCOUNTING_AND_TAX_AUDIT';

export type BcomFinanceMisconceptionId =
  | 'MC_FIN_TIME_VALUE_OF_MONEY_COMPOUND_INTEREST'
  | 'MC_FIN_PRESENT_VALUE_DISCOUNTING_CASH_FLOWS'
  | 'MC_FIN_ANNUITY_ORDINARY_VS_DUE_CALCULATION'
  | 'MC_FIN_BOND_VALUATION_YIELD_TO_MATURITY_YTM'
  | 'MC_FIN_CAPITAL_BUDGETING_NET_PRESENT_VALUE_NPV'
  | 'MC_FIN_INTERNAL_RATE_OF_RETURN_IRR_HURDLE'
  | 'MC_FIN_PAYBACK_PERIOD_AND_DISCOUNTED_PAYBACK'
  | 'MC_FIN_PROFITABILITY_INDEX_PI_PROJECT_RANKING'
  | 'MC_FIN_COST_OF_DEBT_AFTER_TAX_SHIELD'
  | 'MC_FIN_COST_OF_EQUITY_CAPM_AND_DIVIDEND_GROWTH'
  | 'MC_FIN_WEIGHTED_AVERAGE_COST_OF_CAPITAL_WACC'
  | 'MC_FIN_OPERATING_FINANCIAL_COMBINED_LEVERAGE'
  | 'MC_FIN_BREAK_EVEN_POINT_AND_MARGIN_OF_SAFETY'
  | 'MC_FIN_WORKING_CAPITAL_CASH_BUDGETING_FORECAST'
  | 'MC_FIN_CAPITAL_STRUCTURE_MODIGLIANI_MILLER'
  | 'MC_FIN_DIVIDEND_POLICY_WALTER_GORDON_MODELS'
  | 'MC_FIN_EQUITY_VALUATION_DCF_AND_PE_MULTIPLES'
  | 'MC_FIN_MODERN_PORTFOLIO_THEORY_RISK_RETURN_VARIANCE'
  | 'MC_FIN_CAPITAL_ASSET_PRICING_MODEL_CAPM_BETA'
  | 'MC_FIN_SHARPE_TREYNOR_JENSEN_PERFORMANCE_RATIOS'
  | 'MC_FIN_EFFICIENT_MARKET_HYPOTHESIS_EMH_ANOMALIES'
  | 'MC_FIN_DERIVATIVES_FUTURES_FORWARDS_HEDGING'
  | 'MC_FIN_OPTION_PRICING_CALL_PUT_PARITY'
  | 'MC_FIN_FIXED_INCOME_MACAULAY_MODIFIED_DURATION'
  | 'MC_FIN_MERGERS_ACQUISITIONS_ACCRETION_DILUTION'
  | 'MC_FIN_CORPORATE_CREDIT_SCORING_ALTMAN_Z_SCORE'
  | 'MC_FIN_BEHAVIORAL_FINANCE_COGNITIVE_BIASES'
  | 'MC_FIN_FINTECH_ROBO_ADVISORY_ALGORITHMIC_ALLOCATION'
  | 'MC_FIN_ESG_SUSTAINABILITY_INVESTMENT_SCORING'
  | 'MC_FIN_CAPSTONE_CORPORATE_FINANCE_AND_PORTFOLIO_VALUATION';

export type BcomAnalyticsMisconceptionId =
  | 'MC_ANA_DATA_LITERACY_TYPES_NOMINAL_ORDINAL_INTERVAL_RATIO'
  | 'MC_ANA_DESCRIPTIVE_STATS_MEAN_MEDIAN_SKEWNESS'
  | 'MC_ANA_DATA_CLEANING_IMPUTATION_AND_OUTLIERS_IQR'
  | 'MC_ANA_EXPLORATORY_DATA_ANALYSIS_PEARSON_SPEARMAN'
  | 'MC_ANA_PROBABILITY_DISTRIBUTIONS_NORMAL_Z_SCORES'
  | 'MC_ANA_HYPOTHESIS_TESTING_P_VALUE_TYPE_I_II_ERRORS'
  | 'MC_ANA_TWO_SAMPLE_T_TEST_AND_ANOVA_F_STAT'
  | 'MC_ANA_CHI_SQUARE_INDEPENDENCE_CONTINGENCY'
  | 'MC_ANA_SIMPLE_LINEAR_REGRESSION_R_SQUARED_OLS'
  | 'MC_ANA_MULTIPLE_REGRESSION_MULTICOLLINEARITY_VIF'
  | 'MC_ANA_LOGISTIC_REGRESSION_ODDS_RATIO_SIGMOID'
  | 'MC_ANA_CLASSIFICATION_METRICS_PRECISION_RECALL_F1_ROC'
  | 'MC_ANA_CUSTOMER_RFM_SEGMENTATION_ANALYSIS'
  | 'MC_ANA_CUSTOMER_LIFETIME_VALUE_CLV_CHURN'
  | 'MC_ANA_COHORT_ANALYSIS_RETENTION_HEATMAPS'
  | 'MC_ANA_PRICE_ELASTICITY_DEMAND_DYNAMIC_PRICING'
  | 'MC_ANA_TIME_SERIES_FORECASTING_EXPONENTIAL_SMOOTHING'
  | 'MC_ANA_SEASONAL_DECOMPOSITION_TREND_SEASONALITY'
  | 'MC_ANA_INVENTORY_OPTIMIZATION_EOQ_SAFETY_STOCK'
  | 'MC_ANA_SUPPLY_CHAIN_ANALYTICS_OTIF_FILL_RATE'
  | 'MC_ANA_AB_TESTING_SAMPLE_SIZE_STATISTICAL_POWER'
  | 'MC_ANA_EXECUTIVE_DASHBOARD_KPI_BALANCED_SCORECARD'
  | 'MC_ANA_QUEUEING_THEORY_LITTLES_LAW_BOTTLENECK'
  | 'MC_ANA_MARKETING_ATTRIBUTION_MULTI_TOUCH_MODELS'
  | 'MC_ANA_PRESCRIPTIVE_OPTIMIZATION_LINEAR_PROGRAMMING'
  | 'MC_ANA_DECISION_TREES_RANDOM_FORESTS_IMPORTANCE'
  | 'MC_ANA_CLUSTERING_K_MEANS_SILHOUETTE_SCORE'
  | 'MC_ANA_TEXT_ANALYTICS_NLP_SENTIMENT_SCORING'
  | 'MC_ANA_FRAUD_ANOMALY_DETECTION_BENFORD_OUTLIERS'
  | 'MC_ANA_CAPSTONE_ENTERPRISE_BUSINESS_DECISION_INTELLIGENCE';

export type BcomMarketingMisconceptionId =
  | 'MC_MKT_PHILOSOPHIES_SELLING_VS_MARKETING_CONCEPT'
  | 'MC_MKT_ENVIRONMENT_PESTLE_PORTERS_FIVE_FORCES'
  | 'MC_MKT_CONSUMER_BEHAVIOR_BUYING_DECISION_PROCESS'
  | 'MC_MKT_MARKET_RESEARCH_NPS_CALCULATION_SURVEYS'
  | 'MC_MKT_SEGMENTATION_TARGETING_POSITIONING_STP'
  | 'MC_MKT_PRODUCT_LEVELS_CORE_ACTUAL_AUGMENTED'
  | 'MC_MKT_PRODUCT_LIFE_CYCLE_PLC_BCG_MATRIX'
  | 'MC_MKT_BRAND_EQUITY_KELLER_CBBE_PYRAMID'
  | 'MC_MKT_PRICING_STRATEGIES_SKIMMING_PENETRATION_VALUE'
  | 'MC_MKT_DISTRIBUTION_CHANNELS_OMNICHANNEL_CONFLICT'
  | 'MC_MKT_INTEGRATED_MARKETING_COMMUNICATIONS_AIDA'
  | 'MC_MKT_BRAND_POSITIONING_POP_POD_DIFFERENTIATION'
  | 'MC_MKT_SERVICES_MARKETING_7PS_SERVQUAL_GAPS'
  | 'MC_MKT_B2B_BUYING_CENTER_ROLES_PROCUREMENT'
  | 'MC_MKT_DIGITAL_MEDIA_OEP_FRAMEWORK_ENGAGEMENT'
  | 'MC_MKT_CUSTOMER_RELATIONSHIP_MANAGEMENT_CRM_EQUITY'
  | 'MC_MKT_PUBLIC_RELATIONS_CRISIS_COMMUNICATIONS'
  | 'MC_MKT_BRAND_VALUATION_INTERBRAND_ROYALTY'
  | 'MC_MKT_GLOBAL_MARKETING_GLOCALIZATION_STRATEGY'
  | 'MC_MKT_MARKETING_ROI_ROMI_INCREMENTAL_MARGIN'
  | 'MC_MKT_VIRAL_MARKETING_K_FACTOR_COEFFICIENT'
  | 'MC_MKT_GUERILLA_AMBIENT_TACTICAL_MARKETING'
  | 'MC_MKT_INFLUENCER_CO_BRANDING_PARTNERSHIPS'
  | 'MC_MKT_BRAND_REJUVENATION_REPOSITIONING_AUDIT'
  | 'MC_MKT_NEUROMARKETING_DECOY_ANCHORING_NUDGES'
  | 'MC_MKT_GREEN_SUSTAINABILITY_GREENWASHING_AUDIT'
  | 'MC_MKT_AI_PERSONALIZATION_PREDICTIVE_LEADS'
  | 'MC_MKT_MARKETING_ETHICS_ASCI_TRUTH_IN_ADVERTISING'
  | 'MC_MKT_OMNICHANNEL_CUSTOMER_JOURNEY_MAPPING'
  | 'MC_MKT_CAPSTONE_GLOBAL_MARKETING_BRAND_ORCHESTRATION';

export type BcomDigitalMarketingMisconceptionId =
  | 'MC_DMKT_ECOSYSTEM_TOUCHPOINTS_ATTRIBUTION'
  | 'MC_DMKT_SEO_KEYWORD_SEARCH_INTENT_DIFFICULTY'
  | 'MC_DMKT_ONPAGE_TECHNICAL_SEO_CORE_WEB_VITALS'
  | 'MC_DMKT_OFFPAGE_SEO_DOMAIN_AUTHORITY_BACKLINKS'
  | 'MC_DMKT_CONTENT_MARKETING_TOPIC_CLUSTERS_PILLARS'
  | 'MC_DMKT_SEM_GOOGLE_ADS_AUCTION_QUALITY_SCORE'
  | 'MC_DMKT_PPC_BIDDING_TARGET_CPA_TARGET_ROAS'
  | 'MC_DMKT_SMM_META_LOOKALIKE_AUDIENCES_PIXEL'
  | 'MC_DMKT_B2B_LINKEDIN_ACCOUNT_BASED_MARKETING'
  | 'MC_DMKT_VIDEO_MARKETING_HOOK_RATES_RETENTION'
  | 'MC_DMKT_EMAIL_MARKETING_DELIVERABILITY_DMARC_SPF'
  | 'MC_DMKT_MARKETING_AUTOMATION_CART_ABANDONMENT'
  | 'MC_DMKT_CONVERSION_RATE_OPTIMIZATION_AB_TESTING'
  | 'MC_DMKT_LANDING_PAGE_ARCHITECTURE_FRICTION'
  | 'MC_DMKT_GA4_WEB_ANALYTICS_EVENT_DRIVEN_MODEL'
  | 'MC_DMKT_MULTI_TOUCH_ATTRIBUTION_MODELS'
  | 'MC_DMKT_GROWTH_HACKING_AARRR_PIRATE_METRICS'
  | 'MC_DMKT_VIRAL_LOOPS_K_FACTOR_CYCLE_TIME'
  | 'MC_DMKT_APP_STORE_OPTIMIZATION_ASO_RETENTION'
  | 'MC_DMKT_INFLUENCER_AFFILIATE_UTM_TRACKING'
  | 'MC_DMKT_PROGRAMMATIC_RTB_DSP_SSP_VIEWABILITY'
  | 'MC_DMKT_DYNAMIC_RETARGETING_FREQUENCY_CAPPING'
  | 'MC_DMKT_OMNICHANNEL_CLV_TO_CAC_RATIO'
  | 'MC_DMKT_COMMUNITY_COMMERCE_WHATSAPP_D2C'
  | 'MC_DMKT_NEUROMARKETING_SCARCITY_SOCIAL_PROOF'
  | 'MC_DMKT_MARKETING_MIX_MODELING_INCREMENTALITY'
  | 'MC_DMKT_AI_MARKETING_GENERATIVE_CREATIVE_LEADS'
  | 'MC_DMKT_DATA_PRIVACY_GDPR_DPDP_FIRST_PARTY'
  | 'MC_DMKT_BUDGETING_SHARE_OF_VOICE_MEDIA_PLANNING'
  | 'MC_DMKT_CAPSTONE_ENTERPRISE_DIGITAL_GROWTH_SYSTEMS';

export type BcomEcommerceMisconceptionId =
  | 'MC_ECOM_BUSINESS_MODELS_D2C_MARGINS'
  | 'MC_ECOM_PRODUCT_CATALOG_SKU_VARIANTS_TAXONOMY'
  | 'MC_ECOM_PRICING_DYNAMIC_ELASTICITY_MAP'
  | 'MC_ECOM_STORE_UX_PDP_STICKY_BUY_BOX'
  | 'MC_ECOM_CHECKOUT_FRICTION_ONE_PAGE_FLOW'
  | 'MC_ECOM_PAYMENT_GATEWAY_MDR_3DS_SECURITY'
  | 'MC_ECOM_ORDER_MANAGEMENT_STATE_MACHINE_OMS'
  | 'MC_ECOM_INVENTORY_SAFETY_STOCK_REORDER_POINT'
  | 'MC_ECOM_WAREHOUSING_VOLUMETRIC_WEIGHT_PICK_PACK'
  | 'MC_ECOM_LOGISTICS_3PL_COD_RTO_MITIGATION'
  | 'MC_ECOM_REVERSE_LOGISTICS_RMA_RESTOCKING'
  | 'MC_ECOM_MARKETPLACE_AMAZON_BUY_BOX_ONDC'
  | 'MC_ECOM_D2C_HEADLESS_COMMERCE_TECH_STACK'
  | 'MC_ECOM_CUSTOMER_SERVICE_FRT_SLA_POST_PURCHASE'
  | 'MC_ECOM_UNIT_ECONOMICS_GMV_CONTRIBUTION_MARGIN'
  | 'MC_ECOM_COHORT_REPEAT_PURCHASE_RATE_RPR'
  | 'MC_ECOM_FRAUD_PREVENTION_CHARGEBACK_DEFENSE'
  | 'MC_ECOM_OMNICHANNEL_BOPIS_BORIS_POS_SYNC'
  | 'MC_ECOM_CROSS_BORDER_DDP_HS_CODES_CUSTOMS'
  | 'MC_ECOM_SUBSCRIPTION_COMMERCE_MRR_CHURN'
  | 'MC_ECOM_D2C_BRANDING_UNBOXING_EXPERIENCE'
  | 'MC_ECOM_SOCIAL_COMMERCE_LIVE_STREAM_SELLING'
  | 'MC_ECOM_B2B_COMMERCE_NET30_PURCHASE_ORDERS'
  | 'MC_ECOM_DROPSHIPPING_SUPPLIER_SLA_MARGINS'
  | 'MC_ECOM_RECOMMENDATION_ENGINES_CROSS_SELL'
  | 'MC_ECOM_PERSONALIZATION_DYNAMIC_MERCHANDISING'
  | 'MC_ECOM_TAXATION_GST_TCS_EWAY_COMPLIANCE'
  | 'MC_ECOM_SUSTAINABLE_COMMERCE_CIRCULAR_RESALE'
  | 'MC_ECOM_FINANCIAL_SETTLEMENT_RECONCILIATION'
  | 'MC_ECOM_CAPSTONE_ENTERPRISE_OMNICHANNEL_SUITE';

export type BcomEntrepreneurshipMisconceptionId =
  | 'MC_ENT_LEGAL_ENTITIES_PVT_LTD_LIABILITY'
  | 'MC_ENT_OPPORTUNITY_VALIDATION_TAM_SAM_SOM'
  | 'MC_ENT_BUSINESS_MODEL_CANVAS_NINE_BLOCKS'
  | 'MC_ENT_VALUE_PROPOSITION_JTBD_CANVAS'
  | 'MC_ENT_LEAN_STARTUP_MVP_BUILD_MEASURE_LEARN'
  | 'MC_ENT_COMPETITIVE_MOATS_SEVEN_POWERS'
  | 'MC_ENT_FINANCIAL_MODELING_PRO_FORMA_CASH'
  | 'MC_ENT_BREAK_EVEN_ANALYSIS_MARGIN_SAFETY'
  | 'MC_ENT_WORKING_CAPITAL_CASH_RUNWAY_BURN'
  | 'MC_ENT_FUNDING_SAFE_CAP_TABLE_DILUTION'
  | 'MC_ENT_VALUATION_DCF_MULTIPLES_BERKUS'
  | 'MC_ENT_FOUNDER_EQUITY_VESTING_IP_PROTECTION'
  | 'MC_ENT_STRATEGIC_PLANNING_OKRS_ALIGNMENT'
  | 'MC_ENT_OPERATIONS_BPMN_BOTTLENECK_LITTLES_LAW'
  | 'MC_ENT_LEAN_SIX_SIGMA_DMAIC_CPK_QUALITY'
  | 'MC_ENT_SUPPLY_CHAIN_VENDOR_TCO_SLAS'
  | 'MC_ENT_GTM_BEACHHEAD_VIRAL_LOOPS'
  | 'MC_ENT_REVOPS_PIPELINE_COVERAGE_VELOCITY'
  | 'MC_ENT_PRICING_VALUE_BASED_TIERING'
  | 'MC_ENT_UNIT_ECONOMICS_LTV_CAC_PAYBACK'
  | 'MC_ENT_HR_ESOP_POOL_9_BOX_CALIBRATION'
  | 'MC_ENT_LEADERSHIP_SITUATIONAL_PSYCH_SAFETY'
  | 'MC_ENT_GOVERNANCE_BOARD_FIDUCIARY_DUTIES'
  | 'MC_ENT_RISK_MANAGEMENT_ERM_BCP_MATRIX'
  | 'MC_ENT_ETHICS_ESG_TRIPLE_BOTTOM_LINE'
  | 'MC_ENT_INNOVATION_BLUE_OCEAN_ERRC_MODEL'
  | 'MC_ENT_SCALING_GREINER_GROWTH_PHASES'
  | 'MC_ENT_MA_EXIT_STRATEGIES_DUE_DILIGENCE'
  | 'MC_ENT_AI_WORKFLOWS_AUTONOMOUS_OPERATIONS'
  | 'MC_ENT_CAPSTONE_ENTERPRISE_VENTURE_SUITE';

export type BcomSalesCrmMisconceptionId =
  | 'MC_SCRM_SALES_FOUNDATIONS_BUYING_PSYCHOLOGY'
  | 'MC_SCRM_PROSPECTING_ICP_ACCOUNT_CADENCE'
  | 'MC_SCRM_LEAD_QUALIFICATION_MEDDPICC_BANT'
  | 'MC_SCRM_DISCOVERY_CALLS_SPICED_ACTIVE_LISTENING'
  | 'MC_SCRM_PITCHING_FAB_MUTUAL_ACTION_PLANS'
  | 'MC_SCRM_OBJECTION_HANDLING_LAER_FRAMEWORK'
  | 'MC_SCRM_NEGOTIATION_BATNA_ZOPA_VALUE_TRADES'
  | 'MC_SCRM_PIPELINE_MANAGEMENT_STAGE_VELOCITY'
  | 'MC_SCRM_SALES_FORECASTING_CAPACITY_PLANNING'
  | 'MC_SCRM_CUSTOMER_ONBOARDING_TIME_TO_VALUE'
  | 'MC_SCRM_HEALTH_SCORING_CHURN_PREVENTION'
  | 'MC_SCRM_RETENTION_EXPANSION_NRR_GRR'
  | 'MC_SCRM_VOC_NPS_CSAT_ADVOCACY'
  | 'MC_SCRM_KEY_ACCOUNT_MANAGEMENT_WHITESPACE'
  | 'MC_SCRM_CS_OPS_PORTFOLIO_CAPACITY'
  | 'MC_SCRM_CRM_OBJECT_ARCHITECTURE_HYGIENE'
  | 'MC_SCRM_CRM_WORKFLOW_AUTOMATION_ROUTING'
  | 'MC_SCRM_SALES_ENABLEMENT_BATTLECARDS'
  | 'MC_SCRM_COMPENSATION_OTE_ACCELERATORS'
  | 'MC_SCRM_PERFORMANCE_COACHING_TALK_RATIO'
  | 'MC_SCRM_TERRITORY_DESIGN_ACCOUNT_SEGMENTATION'
  | 'MC_SCRM_CHANNEL_SALES_PARTNER_ECOSYSTEMS'
  | 'MC_SCRM_REVOPS_ALIGNMENT_HANDOFF_SLAS'
  | 'MC_SCRM_CONTRACT_MANAGEMENT_MSA_REDLINES'
  | 'MC_SCRM_QBR_VALUE_REALIZATION_REPORTING'
  | 'MC_SCRM_OUTBOUND_DELIVERABILITY_DMARC_WARMUP'
  | 'MC_SCRM_ADVANCED_METHODOLOGY_CHALLENGER_SALE'
  | 'MC_SCRM_SALES_ANALYTICS_WIN_LOSS_METRICS'
  | 'MC_SCRM_AI_SALES_AUTOMATION_COPILOTS'
  | 'MC_SCRM_CAPSTONE_ENTERPRISE_SALES_CRM_SUITE';

export type BcomOperationsMisconceptionId =
  | 'MC_OPS_PROCESS_MAPPING_SIPOC_VALUE_STREAM'
  | 'MC_OPS_INVENTORY_OPTIMIZATION_EOQ_ROP'
  | 'MC_OPS_LOGISTICS_FREIGHT_INCOTERMS_LANDED_COST'
  | 'MC_OPS_DEMAND_FORECASTING_SOP_MAPE'
  | 'MC_OPS_CAPACITY_PLANNING_TOC_OEE'
  | 'MC_OPS_LEAN_OPERATIONS_EIGHT_WASTES_5S'
  | 'MC_OPS_SIX_SIGMA_DMAIC_SPC_CPK'
  | 'MC_OPS_CAPA_FIVE_WHYS_ISHIKAWA_ROOT_CAUSE'
  | 'MC_OPS_PROCUREMENT_KRALJIC_MATRIX_OTIF'
  | 'MC_OPS_CONTRACT_MANUFACTURING_3PL_SLAS'
  | 'MC_OPS_WMS_WAREHOUSE_SLOTTING_CYCLE_COUNT'
  | 'MC_OPS_COLD_CHAIN_HACCP_FEFO_ROTATION'
  | 'MC_OPS_REVERSE_LOGISTICS_CIRCULAR_EPR'
  | 'MC_OPS_CORPORATE_GOVERNANCE_COMPANIES_ACT_ICOFR'
  | 'MC_OPS_LABOR_LAWS_OSHA_EHS_LTIFR'
  | 'MC_OPS_ESG_CARBON_SCOPE_EMISSIONS_ETP'
  | 'MC_OPS_TAX_COMPLIANCE_GST_EINVOICE_3WAY_MATCH'
  | 'MC_OPS_CUSTOMS_FOREIGN_TRADE_HS_CODES'
  | 'MC_OPS_ERM_RISK_MATRIX_BCP_DISASTER_RECOVERY'
  | 'MC_OPS_TPRM_VENDOR_COMPLIANCE_FCPA_ANTI_BRIBERY'
  | 'MC_OPS_TPM_TOTAL_PRODUCTIVE_MAINTENANCE_MTTR'
  | 'MC_OPS_PROJECT_MANAGEMENT_CPM_PERT_CRITICAL_PATH'
  | 'MC_OPS_ERP_SYSTEMS_BOM_EXPLOSION_MRP_NETTING'
  | 'MC_OPS_WORKING_CAPITAL_CASH_CONVERSION_CYCLE'
  | 'MC_OPS_QUALITY_CERTIFICATIONS_ISO_9001_AUDITS'
  | 'MC_OPS_TRADE_SANCTIONS_AML_KYB_CONTROLS'
  | 'MC_OPS_SUPPLY_CHAIN_RESILIENCE_NEARSHORING'
  | 'MC_OPS_SUSTAINABLE_PROCUREMENT_SCOPE_3_AUDITING'
  | 'MC_OPS_AI_AUTONOMOUS_OPERATIONS_PREDICTIVE_OPS'
  | 'MC_OPS_CAPSTONE_ENTERPRISE_OPERATIONS_SUITE';

export type BcomAiTransformationMisconceptionId =
  | 'MC_AIT_AI_LITERACY_BUSINESS_VALUE_EQUATION'
  | 'MC_AIT_PROMPT_ENGINEERING_CREATE_FRAMEWORK'
  | 'MC_AIT_RAG_VECTOR_SIMILARITY_SEARCH'
  | 'MC_AIT_FINANCE_AI_OCR_FRAUD_DETECTION'
  | 'MC_AIT_HR_AI_BIAS_FOUR_FIFTHS_RULE'
  | 'MC_AIT_MARKETING_AI_CLV_DYNAMIC_PRICING'
  | 'MC_AIT_SCM_AI_DEMAND_FORECASTING_INVENTORY'
  | 'MC_AIT_RPA_IDP_STRAIGHT_THROUGH_PROCESSING'
  | 'MC_AIT_BI_PREDICTIVE_ANALYTICS_CHURN'
  | 'MC_AIT_COPILOT_ENTERPRISE_SEMANTIC_SEARCH'
  | 'MC_AIT_NOCODE_AI_CUSTOM_ASSISTANTS'
  | 'MC_AIT_MULTI_AGENT_WORKFLOWS_ORCHESTRATION'
  | 'MC_AIT_CLOUD_AI_TOKEN_ECONOMICS_COST'
  | 'MC_AIT_DATA_ARCHITECTURE_LAKEHOUSE_QUALITY'
  | 'MC_AIT_AI_ETHICS_SHAP_EXPLAINABILITY'
  | 'MC_AIT_AI_GOVERNANCE_EU_AI_ACT_NIST'
  | 'MC_AIT_CYBERSECURITY_PROMPT_INJECTION_DLP'
  | 'MC_AIT_DIGITAL_TRANSFORMATION_KOTTER_MATURITY'
  | 'MC_AIT_AI_PRODUCT_MANAGEMENT_PRECISION_RECALL'
  | 'MC_AIT_CHANGE_MANAGEMENT_AI_COE_CULTURE'
  | 'MC_AIT_CDP_REALTIME_PERSONALIZATION_NBA'
  | 'MC_AIT_AUTONOMOUS_AGENTS_REACT_LOOP'
  | 'MC_AIT_LEGAL_AI_CONTRACT_REDLINING_AUDIT'
  | 'MC_AIT_FINOPS_AI_GPU_UNIT_ECONOMICS'
  | 'MC_AIT_PLATFORM_ECOSYSTEMS_API_MONETIZATION'
  | 'MC_AIT_CONVERSATIONAL_AI_CSAT_ESCALATION'
  | 'MC_AIT_SYNTHETIC_DATA_SIMULATIONS_PERSONAS'
  | 'MC_AIT_STRATEGIC_AI_TCO_BUILD_BUY_PARTNER'
  | 'MC_AIT_AI_LEADERSHIP_BOARDROOM_ROI_REALIZATION'
  | 'MC_AIT_CAPSTONE_ENTERPRISE_AI_TRANSFORMATION_SUITE';

export type ComputerFundamentalsMisconceptionId =
  | 'MC_CF_HARDWARE_CPU_RAM_BUS_BANDWIDTH'
  | 'MC_CF_OS_KERNEL_SYSTEM_CALLS_PROCESS_STATES'
  | 'MC_CF_FILE_SYSTEMS_INODES_POSIX_PERMISSIONS'
  | 'MC_CF_CLI_TERMINAL_PIPING_REDIRECTION'
  | 'MC_CF_PROCESS_MANAGEMENT_PID_CONTEXT_SWITCHING'
  | 'MC_CF_MEMORY_HIERARCHY_CACHE_VIRTUAL_PAGING'
  | 'MC_CF_STORAGE_SSD_NAND_RAID_PARITY'
  | 'MC_CF_NETWORKING_TCP_IP_IPV4_SUBNETTING'
  | 'MC_CF_INTERNET_HTTP_TLS_PORT_MAPPING'
  | 'MC_CF_BROWSER_DEVTOOLS_DOM_LOCALSTORAGE'
  | 'MC_CF_PRODUCTIVITY_TYPING_WPM_SHORTCUTS'
  | 'MC_CF_CLOUD_STORAGE_THREE_TWO_ONE_BACKUP'
  | 'MC_CF_DATA_ENCODING_BINARY_HEX_UTF8'
  | 'MC_CF_CYBERSECURITY_PASSWORD_ENTROPY_MFA'
  | 'MC_CF_OS_SECURITY_UAC_SUDO_PRIVILEGE'
  | 'MC_CF_CRYPTOGRAPHY_AES_RSA_SSH_KEYS'
  | 'MC_CF_PERIPHERALS_USB4_THUNDERBOLT_HDMI'
  | 'MC_CF_PACKAGE_MANAGERS_DEPENDENCY_TREES'
  | 'MC_CF_VIRTUALIZATION_HYPERVISORS_DOCKER'
  | 'MC_CF_TROUBLESHOOTING_SEVEN_STEP_METHODOLOGY'
  | 'MC_CF_AUTOMATION_BASH_POWERSHELL_CRON'
  | 'MC_CF_OFFICE_SUITES_SPREADSHEET_MACROS'
  | 'MC_CF_DATA_PRIVACY_VPN_DOH_TRACKING'
  | 'MC_CF_REMOTE_WORK_SSH_RDP_VDI_TUNNELS'
  | 'MC_CF_HARDWARE_MAINTENANCE_THERMALS_PSU'
  | 'MC_CF_SUSTAINABLE_EWASTE_DOD_WIPE'
  | 'MC_CF_SYSTEM_DIAGNOSTICS_PERFORMANCE_TUNING'
  | 'MC_CF_ENTERPRISE_IT_HELPDESK_ITIL_WORKFLOWS'
  | 'MC_CF_DIGITAL_COLLABORATION_VERSION_HYGIENE'
  | 'MC_CF_CAPSTONE_SOVEREIGN_OS_LITERACY_SUITE';

export type MisconceptionId = JavaMisconceptionId | PythonMisconceptionId | ReactMisconceptionId | SqlMisconceptionId | DsaMisconceptionId | FullstackMisconceptionId | CloudMisconceptionId | DevopsMisconceptionId | AiMisconceptionId | DistributedMisconceptionId | IotEmbeddedMisconceptionId | Graphics3dMisconceptionId | BlockchainMisconceptionId | IotNetworkMisconceptionId | IotEdgeAiMisconceptionId | IotSecurityMisconceptionId | QuantMisconceptionId | BcomAccountingMisconceptionId | BcomFinanceMisconceptionId | BcomAnalyticsMisconceptionId | BcomMarketingMisconceptionId | BcomDigitalMarketingMisconceptionId | BcomEcommerceMisconceptionId | BcomEntrepreneurshipMisconceptionId | BcomSalesCrmMisconceptionId | BcomOperationsMisconceptionId | BcomAiTransformationMisconceptionId | ComputerFundamentalsMisconceptionId;

// ── 3. Strongly-Typed Lesson Media (Zero 'any') ────────────────────────────

export interface MemoryBoxDiagram {
  type: 'memory_box';
  title?: string;
  variableName?: string;
  address?: string;
  value?: string;
  explanation?: string;
  boxes?: Array<{
    label: string;
    value: string;
    varType: string;
    isUpdated?: boolean;
    highlightNote?: string;
  }>;
}

export interface BrokenVsFixedDiff {
  type: 'broken_fixed_diff';
  title?: string;
  brokenCode: string;
  fixedCode: string;
  errorLine?: number;
  errorReason: string;
  fixExplanation: string;
}

export interface SyntaxAnatomyVisual {
  type: 'syntax_anatomy';
  title?: string;
  codeSnippet: string;
  lineNotes: { [line: number]: string };
}

export interface TraceTableDiagram {
  type: 'trace_table';
  title?: string;
  columns: string[];
  steps: Array<{
    stepNumber: number;
    values: { [col: string]: string };
    note: string;
  }>;
}

export interface FlowchartDiagram {
  type: 'flowchart';
  title: string;
  nodes: Array<{
    id: string;
    label: string;
    kind: 'start' | 'decision' | 'process' | 'end';
  }>;
}

export type TypedDiagram =
  | MemoryBoxDiagram
  | BrokenVsFixedDiff
  | SyntaxAnatomyVisual
  | TraceTableDiagram
  | FlowchartDiagram;

export type LessonMedia =
  | { type: 'analogy'; metaphor: string; simpleExplanation: string }
  | { type: 'diagram'; data: TypedDiagram }
  | { type: 'syntax_anatomy'; title?: string; codeSnippet: string; lineNotes: { [line: number]: string } }
  | { type: 'runnable_code'; filename: string; initialCode: string; expectedOutput: string; editable?: boolean };

// ── 4. Multi-Format Socratic Diagnostics ───────────────────────────────────

export type DiagnosticType =
  | 'predict_output'
  | 'choose_answer'
  | 'fix_line'
  | 'trace_value'
  | 'write_code'
  | 'explain_in_words';

export interface DiagnosticCheck {
  type: DiagnosticType;
  question: string;
  codeSnippet?: string;
  options?: string[];
  correctIndex?: number;
  expectedStringOutput?: string;
  acceptableAnswers?: string[];
  primaryMisconceptionId: MisconceptionId;
  diagnosisMap: {
    [errorKeyOrIndex: string]: {
      misconceptionId: MisconceptionId;
      errorExplanation: string;
      recoveryPath: {
        simplerExplanation: string;
        guidedFixPrompt: string;
        prerequisiteReviewId?: string;
      };
    };
  };
}

// ── 5. Micro-Learning Block & Day Lesson Plan ──────────────────────────────

export interface MicroLearningBlock {
  id: string;
  day: number;
  blockNumber: number;
  title: string;
  conceptBudget: {
    primaryConcept: string;
    supportingTerms: string[];
  };
  prerequisiteThresholds: Array<{
    conceptId: string;
    requiredLevel: 'understood' | 'practiced';
  }>;
  media: LessonMedia[];
  diagnosticCheck: DiagnosticCheck;
  novelTransferTask?: {
    prompt: string;
    initialCode: string;
    expectedOutput: string;
  };
}

export interface DayLessonPlan {
  day: number;
  title: string;
  overviewMetaphor: string;
  blocks: MicroLearningBlock[];
  scaffoldedExam?: {
    title: string;
    instruction: string;
    scaffoldLevel: 1 | 2 | 3;
    starterJavaCode: string;
    publicTestCases: Array<{
      description: string;
      input?: string;
      expected: string;
    }>;
  };
  exam?: {
    id?: string;
    day?: number;
    title?: string;
    scaffoldLevel?: any;
    instruction?: string;
    problemDescription?: string;
    starterJavaCode?: string;
    referenceSolution?: string;
    publicTestCases?: any[];
    hiddenTestCases?: any[];
  };
}

// ── 6. Learning Telemetry Events ───────────────────────────────────────────

export type TelemetryEventType =
  | 'block_started'
  | 'sandbox_executed'
  | 'diagnostic_attempted'
  | 'misconception_triggered'
  | 'recovery_entered'
  | 'recovery_guided_retry'
  | 'concept_transferred'
  | 'mentor_escalated'
  | 'hint_used'
  | 'block_passed'
  | 'exam_submitted'
  | 'exam_passed';

export interface LearningTelemetryEvent {
  eventType: TelemetryEventType;
  studentId: string;
  conceptId: string;
  day: number;
  blockNumber?: number;
  timestamp: string;
  metadata?: Record<string, any>;
}
